package dao;

import model.Protocol;
import model.ProtocolExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProtocolMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROTOCOL
     *
     * @mbggenerated
     */
    int countByExample(ProtocolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROTOCOL
     *
     * @mbggenerated
     */
    int deleteByExample(ProtocolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROTOCOL
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROTOCOL
     *
     * @mbggenerated
     */
    int insert(Protocol record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROTOCOL
     *
     * @mbggenerated
     */
    int insertSelective(Protocol record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROTOCOL
     *
     * @mbggenerated
     */
    List<Protocol> selectByExample(ProtocolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROTOCOL
     *
     * @mbggenerated
     */
    Protocol selectByPrimaryKey(Long id);
    
    //Protocol selectByPrimaryKey1(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROTOCOL
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Protocol record, @Param("example") ProtocolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROTOCOL
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Protocol record, @Param("example") ProtocolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROTOCOL
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Protocol record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROTOCOL
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Protocol record);
}