package model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DatapointDatarecordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DATAPOINTDATARECORD
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DATAPOINTDATARECORD
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DATAPOINTDATARECORD
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATAPOINTDATARECORD
     *
     * @mbggenerated
     */
    public DatapointDatarecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATAPOINTDATARECORD
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATAPOINTDATARECORD
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATAPOINTDATARECORD
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATAPOINTDATARECORD
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATAPOINTDATARECORD
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATAPOINTDATARECORD
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATAPOINTDATARECORD
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATAPOINTDATARECORD
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATAPOINTDATARECORD
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATAPOINTDATARECORD
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DATAPOINTDATARECORD
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDatapointidIsNull() {
            addCriterion("DATAPOINTID is null");
            return (Criteria) this;
        }

        public Criteria andDatapointidIsNotNull() {
            addCriterion("DATAPOINTID is not null");
            return (Criteria) this;
        }

        public Criteria andDatapointidEqualTo(Long value) {
            addCriterion("DATAPOINTID =", value, "datapointid");
            return (Criteria) this;
        }

        public Criteria andDatapointidNotEqualTo(Long value) {
            addCriterion("DATAPOINTID <>", value, "datapointid");
            return (Criteria) this;
        }

        public Criteria andDatapointidGreaterThan(Long value) {
            addCriterion("DATAPOINTID >", value, "datapointid");
            return (Criteria) this;
        }

        public Criteria andDatapointidGreaterThanOrEqualTo(Long value) {
            addCriterion("DATAPOINTID >=", value, "datapointid");
            return (Criteria) this;
        }

        public Criteria andDatapointidLessThan(Long value) {
            addCriterion("DATAPOINTID <", value, "datapointid");
            return (Criteria) this;
        }

        public Criteria andDatapointidLessThanOrEqualTo(Long value) {
            addCriterion("DATAPOINTID <=", value, "datapointid");
            return (Criteria) this;
        }

        public Criteria andDatapointidIn(List<Long> values) {
            addCriterion("DATAPOINTID in", values, "datapointid");
            return (Criteria) this;
        }

        public Criteria andDatapointidNotIn(List<Long> values) {
            addCriterion("DATAPOINTID not in", values, "datapointid");
            return (Criteria) this;
        }

        public Criteria andDatapointidBetween(Long value1, Long value2) {
            addCriterion("DATAPOINTID between", value1, value2, "datapointid");
            return (Criteria) this;
        }

        public Criteria andDatapointidNotBetween(Long value1, Long value2) {
            addCriterion("DATAPOINTID not between", value1, value2, "datapointid");
            return (Criteria) this;
        }

        public Criteria andDatarecordidIsNull() {
            addCriterion("DATARECORDID is null");
            return (Criteria) this;
        }

        public Criteria andDatarecordidIsNotNull() {
            addCriterion("DATARECORDID is not null");
            return (Criteria) this;
        }

        public Criteria andDatarecordidEqualTo(Long value) {
            addCriterion("DATARECORDID =", value, "datarecordid");
            return (Criteria) this;
        }
        
        public Criteria andDatarecordidNotEqualTo(Long value) {
            addCriterion("DATARECORDID <>", value, "datarecordid");
            return (Criteria) this;
        }

        public Criteria andDatarecordidGreaterThan(Long value) {
            addCriterion("DATARECORDID >", value, "datarecordid");
            return (Criteria) this;
        }

        public Criteria andDatarecordidGreaterThanOrEqualTo(Long value) {
            addCriterion("DATARECORDID >=", value, "datarecordid");
            return (Criteria) this;
        }

        public Criteria andDatarecordidLessThan(Long value) {
            addCriterion("DATARECORDID <", value, "datarecordid");
            return (Criteria) this;
        }

        public Criteria andDatarecordidLessThanOrEqualTo(Long value) {
            addCriterion("DATARECORDID <=", value, "datarecordid");
            return (Criteria) this;
        }

        public Criteria andDatarecordidIn(List<Long> values) {
            addCriterion("DATARECORDID in", values, "datarecordid");
            return (Criteria) this;
        }

        public Criteria andDatarecordidNotIn(List<Long> values) {
            addCriterion("DATARECORDID not in", values, "datarecordid");
            return (Criteria) this;
        }

        public Criteria andDatarecordidBetween(Long value1, Long value2) {
            addCriterion("DATARECORDID between", value1, value2, "datarecordid");
            return (Criteria) this;
        }

        public Criteria andDatarecordidNotBetween(Long value1, Long value2) {
            addCriterion("DATARECORDID not between", value1, value2, "datarecordid");
            return (Criteria) this;
        }

        public Criteria andValueIsNull() {
            addCriterion("VALUE is null");
            return (Criteria) this;
        }

        public Criteria andValueIsNotNull() {
            addCriterion("VALUE is not null");
            return (Criteria) this;
        }

        public Criteria andValueEqualTo(String value) {
            addCriterion("VALUE =", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueNotEqualTo(String value) {
            addCriterion("VALUE <>", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueGreaterThan(String value) {
            addCriterion("VALUE >", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueGreaterThanOrEqualTo(String value) {
            addCriterion("VALUE >=", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueLessThan(String value) {
            addCriterion("VALUE <", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueLessThanOrEqualTo(String value) {
            addCriterion("VALUE <=", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueLike(String value) {
            addCriterion("VALUE like", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueNotLike(String value) {
            addCriterion("VALUE not like", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueIn(List<String> values) {
            addCriterion("VALUE in", values, "value");
            return (Criteria) this;
        }

        public Criteria andValueNotIn(List<String> values) {
            addCriterion("VALUE not in", values, "value");
            return (Criteria) this;
        }

        public Criteria andValueBetween(String value1, String value2) {
            addCriterion("VALUE between", value1, value2, "value");
            return (Criteria) this;
        }

        public Criteria andValueNotBetween(String value1, String value2) {
            addCriterion("VALUE not between", value1, value2, "value");
            return (Criteria) this;
        }

        public Criteria andCreatoridIsNull() {
            addCriterion("CREATORID is null");
            return (Criteria) this;
        }

        public Criteria andCreatoridIsNotNull() {
            addCriterion("CREATORID is not null");
            return (Criteria) this;
        }

        public Criteria andCreatoridEqualTo(String value) {
            addCriterion("CREATORID =", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridNotEqualTo(String value) {
            addCriterion("CREATORID <>", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridGreaterThan(String value) {
            addCriterion("CREATORID >", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridGreaterThanOrEqualTo(String value) {
            addCriterion("CREATORID >=", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridLessThan(String value) {
            addCriterion("CREATORID <", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridLessThanOrEqualTo(String value) {
            addCriterion("CREATORID <=", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridLike(String value) {
            addCriterion("CREATORID like", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridNotLike(String value) {
            addCriterion("CREATORID not like", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridIn(List<String> values) {
            addCriterion("CREATORID in", values, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridNotIn(List<String> values) {
            addCriterion("CREATORID not in", values, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridBetween(String value1, String value2) {
            addCriterion("CREATORID between", value1, value2, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridNotBetween(String value1, String value2) {
            addCriterion("CREATORID not between", value1, value2, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreateddateIsNull() {
            addCriterion("CREATEDDATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateddateIsNotNull() {
            addCriterion("CREATEDDATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateddateEqualTo(Date value) {
            addCriterion("CREATEDDATE =", value, "createddate");
            return (Criteria) this;
        }

        public Criteria andCreateddateNotEqualTo(Date value) {
            addCriterion("CREATEDDATE <>", value, "createddate");
            return (Criteria) this;
        }

        public Criteria andCreateddateGreaterThan(Date value) {
            addCriterion("CREATEDDATE >", value, "createddate");
            return (Criteria) this;
        }

        public Criteria andCreateddateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATEDDATE >=", value, "createddate");
            return (Criteria) this;
        }

        public Criteria andCreateddateLessThan(Date value) {
            addCriterion("CREATEDDATE <", value, "createddate");
            return (Criteria) this;
        }

        public Criteria andCreateddateLessThanOrEqualTo(Date value) {
            addCriterion("CREATEDDATE <=", value, "createddate");
            return (Criteria) this;
        }

        public Criteria andCreateddateIn(List<Date> values) {
            addCriterion("CREATEDDATE in", values, "createddate");
            return (Criteria) this;
        }

        public Criteria andCreateddateNotIn(List<Date> values) {
            addCriterion("CREATEDDATE not in", values, "createddate");
            return (Criteria) this;
        }

        public Criteria andCreateddateBetween(Date value1, Date value2) {
            addCriterion("CREATEDDATE between", value1, value2, "createddate");
            return (Criteria) this;
        }

        public Criteria andCreateddateNotBetween(Date value1, Date value2) {
            addCriterion("CREATEDDATE not between", value1, value2, "createddate");
            return (Criteria) this;
        }

        public Criteria andLastupdidIsNull() {
            addCriterion("LASTUPDID is null");
            return (Criteria) this;
        }

        public Criteria andLastupdidIsNotNull() {
            addCriterion("LASTUPDID is not null");
            return (Criteria) this;
        }

        public Criteria andLastupdidEqualTo(String value) {
            addCriterion("LASTUPDID =", value, "lastupdid");
            return (Criteria) this;
        }

        public Criteria andLastupdidNotEqualTo(String value) {
            addCriterion("LASTUPDID <>", value, "lastupdid");
            return (Criteria) this;
        }

        public Criteria andLastupdidGreaterThan(String value) {
            addCriterion("LASTUPDID >", value, "lastupdid");
            return (Criteria) this;
        }

        public Criteria andLastupdidGreaterThanOrEqualTo(String value) {
            addCriterion("LASTUPDID >=", value, "lastupdid");
            return (Criteria) this;
        }

        public Criteria andLastupdidLessThan(String value) {
            addCriterion("LASTUPDID <", value, "lastupdid");
            return (Criteria) this;
        }

        public Criteria andLastupdidLessThanOrEqualTo(String value) {
            addCriterion("LASTUPDID <=", value, "lastupdid");
            return (Criteria) this;
        }

        public Criteria andLastupdidLike(String value) {
            addCriterion("LASTUPDID like", value, "lastupdid");
            return (Criteria) this;
        }

        public Criteria andLastupdidNotLike(String value) {
            addCriterion("LASTUPDID not like", value, "lastupdid");
            return (Criteria) this;
        }

        public Criteria andLastupdidIn(List<String> values) {
            addCriterion("LASTUPDID in", values, "lastupdid");
            return (Criteria) this;
        }

        public Criteria andLastupdidNotIn(List<String> values) {
            addCriterion("LASTUPDID not in", values, "lastupdid");
            return (Criteria) this;
        }

        public Criteria andLastupdidBetween(String value1, String value2) {
            addCriterion("LASTUPDID between", value1, value2, "lastupdid");
            return (Criteria) this;
        }

        public Criteria andLastupdidNotBetween(String value1, String value2) {
            addCriterion("LASTUPDID not between", value1, value2, "lastupdid");
            return (Criteria) this;
        }

        public Criteria andLastupddateIsNull() {
            addCriterion("LASTUPDDATE is null");
            return (Criteria) this;
        }

        public Criteria andLastupddateIsNotNull() {
            addCriterion("LASTUPDDATE is not null");
            return (Criteria) this;
        }

        public Criteria andLastupddateEqualTo(Date value) {
            addCriterion("LASTUPDDATE =", value, "lastupddate");
            return (Criteria) this;
        }

        public Criteria andLastupddateNotEqualTo(Date value) {
            addCriterion("LASTUPDDATE <>", value, "lastupddate");
            return (Criteria) this;
        }

        public Criteria andLastupddateGreaterThan(Date value) {
            addCriterion("LASTUPDDATE >", value, "lastupddate");
            return (Criteria) this;
        }

        public Criteria andLastupddateGreaterThanOrEqualTo(Date value) {
            addCriterion("LASTUPDDATE >=", value, "lastupddate");
            return (Criteria) this;
        }

        public Criteria andLastupddateLessThan(Date value) {
            addCriterion("LASTUPDDATE <", value, "lastupddate");
            return (Criteria) this;
        }

        public Criteria andLastupddateLessThanOrEqualTo(Date value) {
            addCriterion("LASTUPDDATE <=", value, "lastupddate");
            return (Criteria) this;
        }

        public Criteria andLastupddateIn(List<Date> values) {
            addCriterion("LASTUPDDATE in", values, "lastupddate");
            return (Criteria) this;
        }

        public Criteria andLastupddateNotIn(List<Date> values) {
            addCriterion("LASTUPDDATE not in", values, "lastupddate");
            return (Criteria) this;
        }

        public Criteria andLastupddateBetween(Date value1, Date value2) {
            addCriterion("LASTUPDDATE between", value1, value2, "lastupddate");
            return (Criteria) this;
        }

        public Criteria andLastupddateNotBetween(Date value1, Date value2) {
            addCriterion("LASTUPDDATE not between", value1, value2, "lastupddate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DATAPOINTDATARECORD
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DATAPOINTDATARECORD
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}