package model;

import java.util.List;

public class Form {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to
   * the database column FORM.ID
   *
   * @mbggenerated
   */
  private Long id;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to
   * the database column FORM.TITLE
   *
   * @mbggenerated
   */
  private String title;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to
   * the database column FORM.DCPID
   *
   * @mbggenerated
   */
  private Long dcpid;

  
  private List<FormVersionTest> fv;
  
  public List<FormVersionTest> getFvid() {
    return fv;
  }

  public void setFvid(List<FormVersionTest> fv) {
    this.fv = fv;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the
   * value of the database column FORM.TITLE
   *
   * @return the value of FORM.TITLE
   *
   * @mbggenerated
   */
  public String getTitle() {
    return title;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value
   * of the database column FORM.TITLE
   *
   * @param title
   *          the value for FORM.TITLE
   *
   * @mbggenerated
   */
  public void setTitle(String title) {
    this.title = title == null ? null : title.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the
   * value of the database column FORM.ID
   *
   * @return the value of FORM.ID
   *
   * @mbggenerated
   */
  public Long getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value
   * of the database column FORM.ID
   *
   * @param id
   *          the value for FORM.ID
   *
   * @mbggenerated
   */
  public void setId(Long id) {
    this.id = id;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the
   * value of the database column FORM.DCPID
   *
   * @return the value of FORM.DCPID
   *
   * @mbggenerated
   */
  public Long getDcpid() {
    return dcpid;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value
   * of the database column FORM.DCPID
   *
   * @param dcpid
   *          the value for FORM.DCPID
   *
   * @mbggenerated
   */
  public void setDcpid(Long dcpid) {
    this.dcpid = dcpid;
  }

}