package model;

import java.util.ArrayList;
import java.util.List;

public class FormExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FORM
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FORM
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FORM
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FORM
     *
     * @mbggenerated
     */
    public FormExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FORM
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FORM
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FORM
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FORM
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FORM
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FORM
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FORM
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FORM
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FORM
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FORM
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FORM
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTitleIsNull() {
            addCriterion("TITLE is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("TITLE is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("TITLE =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("TITLE <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("TITLE >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("TITLE >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("TITLE <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("TITLE <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("TITLE like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("TITLE not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("TITLE in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("TITLE not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("TITLE between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("TITLE not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andCompleteByIsNull() {
            addCriterion("COMPLETE_BY is null");
            return (Criteria) this;
        }

        public Criteria andCompleteByIsNotNull() {
            addCriterion("COMPLETE_BY is not null");
            return (Criteria) this;
        }

        public Criteria andCompleteByEqualTo(String value) {
            addCriterion("COMPLETE_BY =", value, "completeBy");
            return (Criteria) this;
        }

        public Criteria andCompleteByNotEqualTo(String value) {
            addCriterion("COMPLETE_BY <>", value, "completeBy");
            return (Criteria) this;
        }

        public Criteria andCompleteByGreaterThan(String value) {
            addCriterion("COMPLETE_BY >", value, "completeBy");
            return (Criteria) this;
        }

        public Criteria andCompleteByGreaterThanOrEqualTo(String value) {
            addCriterion("COMPLETE_BY >=", value, "completeBy");
            return (Criteria) this;
        }

        public Criteria andCompleteByLessThan(String value) {
            addCriterion("COMPLETE_BY <", value, "completeBy");
            return (Criteria) this;
        }

        public Criteria andCompleteByLessThanOrEqualTo(String value) {
            addCriterion("COMPLETE_BY <=", value, "completeBy");
            return (Criteria) this;
        }

        public Criteria andCompleteByLike(String value) {
            addCriterion("COMPLETE_BY like", value, "completeBy");
            return (Criteria) this;
        }

        public Criteria andCompleteByNotLike(String value) {
            addCriterion("COMPLETE_BY not like", value, "completeBy");
            return (Criteria) this;
        }

        public Criteria andCompleteByIn(List<String> values) {
            addCriterion("COMPLETE_BY in", values, "completeBy");
            return (Criteria) this;
        }

        public Criteria andCompleteByNotIn(List<String> values) {
            addCriterion("COMPLETE_BY not in", values, "completeBy");
            return (Criteria) this;
        }

        public Criteria andCompleteByBetween(String value1, String value2) {
            addCriterion("COMPLETE_BY between", value1, value2, "completeBy");
            return (Criteria) this;
        }

        public Criteria andCompleteByNotBetween(String value1, String value2) {
            addCriterion("COMPLETE_BY not between", value1, value2, "completeBy");
            return (Criteria) this;
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("TYPE is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("TYPE =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("TYPE <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("TYPE >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("TYPE >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("TYPE <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("TYPE <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("TYPE like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("TYPE not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("TYPE in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("TYPE not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("TYPE between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("TYPE not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andUrlIsNull() {
            addCriterion("URL is null");
            return (Criteria) this;
        }

        public Criteria andUrlIsNotNull() {
            addCriterion("URL is not null");
            return (Criteria) this;
        }

        public Criteria andUrlEqualTo(String value) {
            addCriterion("URL =", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotEqualTo(String value) {
            addCriterion("URL <>", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThan(String value) {
            addCriterion("URL >", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThanOrEqualTo(String value) {
            addCriterion("URL >=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThan(String value) {
            addCriterion("URL <", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThanOrEqualTo(String value) {
            addCriterion("URL <=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLike(String value) {
            addCriterion("URL like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotLike(String value) {
            addCriterion("URL not like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlIn(List<String> values) {
            addCriterion("URL in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotIn(List<String> values) {
            addCriterion("URL not in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlBetween(String value1, String value2) {
            addCriterion("URL between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotBetween(String value1, String value2) {
            addCriterion("URL not between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andDcpidIsNull() {
            addCriterion("DCPID is null");
            return (Criteria) this;
        }

        public Criteria andDcpidIsNotNull() {
            addCriterion("DCPID is not null");
            return (Criteria) this;
        }

        public Criteria andDcpidEqualTo(Long value) {
            addCriterion("DCPID =", value, "dcpid");
            return (Criteria) this;
        }

        public Criteria andDcpidNotEqualTo(Long value) {
            addCriterion("DCPID <>", value, "dcpid");
            return (Criteria) this;
        }

        public Criteria andDcpidGreaterThan(Long value) {
            addCriterion("DCPID >", value, "dcpid");
            return (Criteria) this;
        }

        public Criteria andDcpidGreaterThanOrEqualTo(Long value) {
            addCriterion("DCPID >=", value, "dcpid");
            return (Criteria) this;
        }

        public Criteria andDcpidLessThan(Long value) {
            addCriterion("DCPID <", value, "dcpid");
            return (Criteria) this;
        }

        public Criteria andDcpidLessThanOrEqualTo(Long value) {
            addCriterion("DCPID <=", value, "dcpid");
            return (Criteria) this;
        }

        public Criteria andDcpidIn(List<Long> values) {
            addCriterion("DCPID in", values, "dcpid");
            return (Criteria) this;
        }

        public Criteria andDcpidNotIn(List<Long> values) {
            addCriterion("DCPID not in", values, "dcpid");
            return (Criteria) this;
        }

        public Criteria andDcpidBetween(Long value1, Long value2) {
            addCriterion("DCPID between", value1, value2, "dcpid");
            return (Criteria) this;
        }

        public Criteria andDcpidNotBetween(Long value1, Long value2) {
            addCriterion("DCPID not between", value1, value2, "dcpid");
            return (Criteria) this;
        }

        public Criteria andInternalCodeIsNull() {
            addCriterion("INTERNAL_CODE is null");
            return (Criteria) this;
        }

        public Criteria andInternalCodeIsNotNull() {
            addCriterion("INTERNAL_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andInternalCodeEqualTo(String value) {
            addCriterion("INTERNAL_CODE =", value, "internalCode");
            return (Criteria) this;
        }

        public Criteria andInternalCodeNotEqualTo(String value) {
            addCriterion("INTERNAL_CODE <>", value, "internalCode");
            return (Criteria) this;
        }

        public Criteria andInternalCodeGreaterThan(String value) {
            addCriterion("INTERNAL_CODE >", value, "internalCode");
            return (Criteria) this;
        }

        public Criteria andInternalCodeGreaterThanOrEqualTo(String value) {
            addCriterion("INTERNAL_CODE >=", value, "internalCode");
            return (Criteria) this;
        }

        public Criteria andInternalCodeLessThan(String value) {
            addCriterion("INTERNAL_CODE <", value, "internalCode");
            return (Criteria) this;
        }

        public Criteria andInternalCodeLessThanOrEqualTo(String value) {
            addCriterion("INTERNAL_CODE <=", value, "internalCode");
            return (Criteria) this;
        }

        public Criteria andInternalCodeLike(String value) {
            addCriterion("INTERNAL_CODE like", value, "internalCode");
            return (Criteria) this;
        }

        public Criteria andInternalCodeNotLike(String value) {
            addCriterion("INTERNAL_CODE not like", value, "internalCode");
            return (Criteria) this;
        }

        public Criteria andInternalCodeIn(List<String> values) {
            addCriterion("INTERNAL_CODE in", values, "internalCode");
            return (Criteria) this;
        }

        public Criteria andInternalCodeNotIn(List<String> values) {
            addCriterion("INTERNAL_CODE not in", values, "internalCode");
            return (Criteria) this;
        }

        public Criteria andInternalCodeBetween(String value1, String value2) {
            addCriterion("INTERNAL_CODE between", value1, value2, "internalCode");
            return (Criteria) this;
        }

        public Criteria andInternalCodeNotBetween(String value1, String value2) {
            addCriterion("INTERNAL_CODE not between", value1, value2, "internalCode");
            return (Criteria) this;
        }

        public Criteria andIndependentFilloutFlgIsNull() {
            addCriterion("INDEPENDENT_FILLOUT_FLG is null");
            return (Criteria) this;
        }

        public Criteria andIndependentFilloutFlgIsNotNull() {
            addCriterion("INDEPENDENT_FILLOUT_FLG is not null");
            return (Criteria) this;
        }

        public Criteria andIndependentFilloutFlgEqualTo(String value) {
            addCriterion("INDEPENDENT_FILLOUT_FLG =", value, "independentFilloutFlg");
            return (Criteria) this;
        }

        public Criteria andIndependentFilloutFlgNotEqualTo(String value) {
            addCriterion("INDEPENDENT_FILLOUT_FLG <>", value, "independentFilloutFlg");
            return (Criteria) this;
        }

        public Criteria andIndependentFilloutFlgGreaterThan(String value) {
            addCriterion("INDEPENDENT_FILLOUT_FLG >", value, "independentFilloutFlg");
            return (Criteria) this;
        }

        public Criteria andIndependentFilloutFlgGreaterThanOrEqualTo(String value) {
            addCriterion("INDEPENDENT_FILLOUT_FLG >=", value, "independentFilloutFlg");
            return (Criteria) this;
        }

        public Criteria andIndependentFilloutFlgLessThan(String value) {
            addCriterion("INDEPENDENT_FILLOUT_FLG <", value, "independentFilloutFlg");
            return (Criteria) this;
        }

        public Criteria andIndependentFilloutFlgLessThanOrEqualTo(String value) {
            addCriterion("INDEPENDENT_FILLOUT_FLG <=", value, "independentFilloutFlg");
            return (Criteria) this;
        }

        public Criteria andIndependentFilloutFlgLike(String value) {
            addCriterion("INDEPENDENT_FILLOUT_FLG like", value, "independentFilloutFlg");
            return (Criteria) this;
        }

        public Criteria andIndependentFilloutFlgNotLike(String value) {
            addCriterion("INDEPENDENT_FILLOUT_FLG not like", value, "independentFilloutFlg");
            return (Criteria) this;
        }

        public Criteria andIndependentFilloutFlgIn(List<String> values) {
            addCriterion("INDEPENDENT_FILLOUT_FLG in", values, "independentFilloutFlg");
            return (Criteria) this;
        }

        public Criteria andIndependentFilloutFlgNotIn(List<String> values) {
            addCriterion("INDEPENDENT_FILLOUT_FLG not in", values, "independentFilloutFlg");
            return (Criteria) this;
        }

        public Criteria andIndependentFilloutFlgBetween(String value1, String value2) {
            addCriterion("INDEPENDENT_FILLOUT_FLG between", value1, value2, "independentFilloutFlg");
            return (Criteria) this;
        }

        public Criteria andIndependentFilloutFlgNotBetween(String value1, String value2) {
            addCriterion("INDEPENDENT_FILLOUT_FLG not between", value1, value2, "independentFilloutFlg");
            return (Criteria) this;
        }

        public Criteria andLockversionFlgIsNull() {
            addCriterion("LOCKVERSION_FLG is null");
            return (Criteria) this;
        }

        public Criteria andLockversionFlgIsNotNull() {
            addCriterion("LOCKVERSION_FLG is not null");
            return (Criteria) this;
        }

        public Criteria andLockversionFlgEqualTo(String value) {
            addCriterion("LOCKVERSION_FLG =", value, "lockversionFlg");
            return (Criteria) this;
        }

        public Criteria andLockversionFlgNotEqualTo(String value) {
            addCriterion("LOCKVERSION_FLG <>", value, "lockversionFlg");
            return (Criteria) this;
        }

        public Criteria andLockversionFlgGreaterThan(String value) {
            addCriterion("LOCKVERSION_FLG >", value, "lockversionFlg");
            return (Criteria) this;
        }

        public Criteria andLockversionFlgGreaterThanOrEqualTo(String value) {
            addCriterion("LOCKVERSION_FLG >=", value, "lockversionFlg");
            return (Criteria) this;
        }

        public Criteria andLockversionFlgLessThan(String value) {
            addCriterion("LOCKVERSION_FLG <", value, "lockversionFlg");
            return (Criteria) this;
        }

        public Criteria andLockversionFlgLessThanOrEqualTo(String value) {
            addCriterion("LOCKVERSION_FLG <=", value, "lockversionFlg");
            return (Criteria) this;
        }

        public Criteria andLockversionFlgLike(String value) {
            addCriterion("LOCKVERSION_FLG like", value, "lockversionFlg");
            return (Criteria) this;
        }

        public Criteria andLockversionFlgNotLike(String value) {
            addCriterion("LOCKVERSION_FLG not like", value, "lockversionFlg");
            return (Criteria) this;
        }

        public Criteria andLockversionFlgIn(List<String> values) {
            addCriterion("LOCKVERSION_FLG in", values, "lockversionFlg");
            return (Criteria) this;
        }

        public Criteria andLockversionFlgNotIn(List<String> values) {
            addCriterion("LOCKVERSION_FLG not in", values, "lockversionFlg");
            return (Criteria) this;
        }

        public Criteria andLockversionFlgBetween(String value1, String value2) {
            addCriterion("LOCKVERSION_FLG between", value1, value2, "lockversionFlg");
            return (Criteria) this;
        }

        public Criteria andLockversionFlgNotBetween(String value1, String value2) {
            addCriterion("LOCKVERSION_FLG not between", value1, value2, "lockversionFlg");
            return (Criteria) this;
        }

        public Criteria andPclgroupIdIsNull() {
            addCriterion("PCLGROUP_ID is null");
            return (Criteria) this;
        }

        public Criteria andPclgroupIdIsNotNull() {
            addCriterion("PCLGROUP_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPclgroupIdEqualTo(Long value) {
            addCriterion("PCLGROUP_ID =", value, "pclgroupId");
            return (Criteria) this;
        }

        public Criteria andPclgroupIdNotEqualTo(Long value) {
            addCriterion("PCLGROUP_ID <>", value, "pclgroupId");
            return (Criteria) this;
        }

        public Criteria andPclgroupIdGreaterThan(Long value) {
            addCriterion("PCLGROUP_ID >", value, "pclgroupId");
            return (Criteria) this;
        }

        public Criteria andPclgroupIdGreaterThanOrEqualTo(Long value) {
            addCriterion("PCLGROUP_ID >=", value, "pclgroupId");
            return (Criteria) this;
        }

        public Criteria andPclgroupIdLessThan(Long value) {
            addCriterion("PCLGROUP_ID <", value, "pclgroupId");
            return (Criteria) this;
        }

        public Criteria andPclgroupIdLessThanOrEqualTo(Long value) {
            addCriterion("PCLGROUP_ID <=", value, "pclgroupId");
            return (Criteria) this;
        }

        public Criteria andPclgroupIdIn(List<Long> values) {
            addCriterion("PCLGROUP_ID in", values, "pclgroupId");
            return (Criteria) this;
        }

        public Criteria andPclgroupIdNotIn(List<Long> values) {
            addCriterion("PCLGROUP_ID not in", values, "pclgroupId");
            return (Criteria) this;
        }

        public Criteria andPclgroupIdBetween(Long value1, Long value2) {
            addCriterion("PCLGROUP_ID between", value1, value2, "pclgroupId");
            return (Criteria) this;
        }

        public Criteria andPclgroupIdNotBetween(Long value1, Long value2) {
            addCriterion("PCLGROUP_ID not between", value1, value2, "pclgroupId");
            return (Criteria) this;
        }

        public Criteria andPrePopFlgIsNull() {
            addCriterion("PRE_POP_FLG is null");
            return (Criteria) this;
        }

        public Criteria andPrePopFlgIsNotNull() {
            addCriterion("PRE_POP_FLG is not null");
            return (Criteria) this;
        }

        public Criteria andPrePopFlgEqualTo(String value) {
            addCriterion("PRE_POP_FLG =", value, "prePopFlg");
            return (Criteria) this;
        }

        public Criteria andPrePopFlgNotEqualTo(String value) {
            addCriterion("PRE_POP_FLG <>", value, "prePopFlg");
            return (Criteria) this;
        }

        public Criteria andPrePopFlgGreaterThan(String value) {
            addCriterion("PRE_POP_FLG >", value, "prePopFlg");
            return (Criteria) this;
        }

        public Criteria andPrePopFlgGreaterThanOrEqualTo(String value) {
            addCriterion("PRE_POP_FLG >=", value, "prePopFlg");
            return (Criteria) this;
        }

        public Criteria andPrePopFlgLessThan(String value) {
            addCriterion("PRE_POP_FLG <", value, "prePopFlg");
            return (Criteria) this;
        }

        public Criteria andPrePopFlgLessThanOrEqualTo(String value) {
            addCriterion("PRE_POP_FLG <=", value, "prePopFlg");
            return (Criteria) this;
        }

        public Criteria andPrePopFlgLike(String value) {
            addCriterion("PRE_POP_FLG like", value, "prePopFlg");
            return (Criteria) this;
        }

        public Criteria andPrePopFlgNotLike(String value) {
            addCriterion("PRE_POP_FLG not like", value, "prePopFlg");
            return (Criteria) this;
        }

        public Criteria andPrePopFlgIn(List<String> values) {
            addCriterion("PRE_POP_FLG in", values, "prePopFlg");
            return (Criteria) this;
        }

        public Criteria andPrePopFlgNotIn(List<String> values) {
            addCriterion("PRE_POP_FLG not in", values, "prePopFlg");
            return (Criteria) this;
        }

        public Criteria andPrePopFlgBetween(String value1, String value2) {
            addCriterion("PRE_POP_FLG between", value1, value2, "prePopFlg");
            return (Criteria) this;
        }

        public Criteria andPrePopFlgNotBetween(String value1, String value2) {
            addCriterion("PRE_POP_FLG not between", value1, value2, "prePopFlg");
            return (Criteria) this;
        }

        public Criteria andDisplayPreviousFlgIsNull() {
            addCriterion("DISPLAY_PREVIOUS_FLG is null");
            return (Criteria) this;
        }

        public Criteria andDisplayPreviousFlgIsNotNull() {
            addCriterion("DISPLAY_PREVIOUS_FLG is not null");
            return (Criteria) this;
        }

        public Criteria andDisplayPreviousFlgEqualTo(String value) {
            addCriterion("DISPLAY_PREVIOUS_FLG =", value, "displayPreviousFlg");
            return (Criteria) this;
        }

        public Criteria andDisplayPreviousFlgNotEqualTo(String value) {
            addCriterion("DISPLAY_PREVIOUS_FLG <>", value, "displayPreviousFlg");
            return (Criteria) this;
        }

        public Criteria andDisplayPreviousFlgGreaterThan(String value) {
            addCriterion("DISPLAY_PREVIOUS_FLG >", value, "displayPreviousFlg");
            return (Criteria) this;
        }

        public Criteria andDisplayPreviousFlgGreaterThanOrEqualTo(String value) {
            addCriterion("DISPLAY_PREVIOUS_FLG >=", value, "displayPreviousFlg");
            return (Criteria) this;
        }

        public Criteria andDisplayPreviousFlgLessThan(String value) {
            addCriterion("DISPLAY_PREVIOUS_FLG <", value, "displayPreviousFlg");
            return (Criteria) this;
        }

        public Criteria andDisplayPreviousFlgLessThanOrEqualTo(String value) {
            addCriterion("DISPLAY_PREVIOUS_FLG <=", value, "displayPreviousFlg");
            return (Criteria) this;
        }

        public Criteria andDisplayPreviousFlgLike(String value) {
            addCriterion("DISPLAY_PREVIOUS_FLG like", value, "displayPreviousFlg");
            return (Criteria) this;
        }

        public Criteria andDisplayPreviousFlgNotLike(String value) {
            addCriterion("DISPLAY_PREVIOUS_FLG not like", value, "displayPreviousFlg");
            return (Criteria) this;
        }

        public Criteria andDisplayPreviousFlgIn(List<String> values) {
            addCriterion("DISPLAY_PREVIOUS_FLG in", values, "displayPreviousFlg");
            return (Criteria) this;
        }

        public Criteria andDisplayPreviousFlgNotIn(List<String> values) {
            addCriterion("DISPLAY_PREVIOUS_FLG not in", values, "displayPreviousFlg");
            return (Criteria) this;
        }

        public Criteria andDisplayPreviousFlgBetween(String value1, String value2) {
            addCriterion("DISPLAY_PREVIOUS_FLG between", value1, value2, "displayPreviousFlg");
            return (Criteria) this;
        }

        public Criteria andDisplayPreviousFlgNotBetween(String value1, String value2) {
            addCriterion("DISPLAY_PREVIOUS_FLG not between", value1, value2, "displayPreviousFlg");
            return (Criteria) this;
        }

        public Criteria andPreFillFlgIsNull() {
            addCriterion("PRE_FILL_FLG is null");
            return (Criteria) this;
        }

        public Criteria andPreFillFlgIsNotNull() {
            addCriterion("PRE_FILL_FLG is not null");
            return (Criteria) this;
        }

        public Criteria andPreFillFlgEqualTo(String value) {
            addCriterion("PRE_FILL_FLG =", value, "preFillFlg");
            return (Criteria) this;
        }

        public Criteria andPreFillFlgNotEqualTo(String value) {
            addCriterion("PRE_FILL_FLG <>", value, "preFillFlg");
            return (Criteria) this;
        }

        public Criteria andPreFillFlgGreaterThan(String value) {
            addCriterion("PRE_FILL_FLG >", value, "preFillFlg");
            return (Criteria) this;
        }

        public Criteria andPreFillFlgGreaterThanOrEqualTo(String value) {
            addCriterion("PRE_FILL_FLG >=", value, "preFillFlg");
            return (Criteria) this;
        }

        public Criteria andPreFillFlgLessThan(String value) {
            addCriterion("PRE_FILL_FLG <", value, "preFillFlg");
            return (Criteria) this;
        }

        public Criteria andPreFillFlgLessThanOrEqualTo(String value) {
            addCriterion("PRE_FILL_FLG <=", value, "preFillFlg");
            return (Criteria) this;
        }

        public Criteria andPreFillFlgLike(String value) {
            addCriterion("PRE_FILL_FLG like", value, "preFillFlg");
            return (Criteria) this;
        }

        public Criteria andPreFillFlgNotLike(String value) {
            addCriterion("PRE_FILL_FLG not like", value, "preFillFlg");
            return (Criteria) this;
        }

        public Criteria andPreFillFlgIn(List<String> values) {
            addCriterion("PRE_FILL_FLG in", values, "preFillFlg");
            return (Criteria) this;
        }

        public Criteria andPreFillFlgNotIn(List<String> values) {
            addCriterion("PRE_FILL_FLG not in", values, "preFillFlg");
            return (Criteria) this;
        }

        public Criteria andPreFillFlgBetween(String value1, String value2) {
            addCriterion("PRE_FILL_FLG between", value1, value2, "preFillFlg");
            return (Criteria) this;
        }

        public Criteria andPreFillFlgNotBetween(String value1, String value2) {
            addCriterion("PRE_FILL_FLG not between", value1, value2, "preFillFlg");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FORM
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FORM
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}