package model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class PatientExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PATIENT
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PATIENT
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PATIENT
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATIENT
     *
     * @mbggenerated
     */
    public PatientExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATIENT
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATIENT
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATIENT
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATIENT
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATIENT
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATIENT
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATIENT
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATIENT
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATIENT
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATIENT
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PATIENT
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andPatientidIsNull() {
            addCriterion("PATIENTID is null");
            return (Criteria) this;
        }

        public Criteria andPatientidIsNotNull() {
            addCriterion("PATIENTID is not null");
            return (Criteria) this;
        }

        public Criteria andPatientidEqualTo(Long value) {
            addCriterion("PATIENT.PATIENTID =", value, "id");
            return (Criteria) this;
        }
        
        public Criteria andProtocolidEqualTo(Long value) {
          addCriterion("PROTOCOL_PATIENT.PROTOCOLID =", value, "protocolid");
          return (Criteria) this;
        }

        public Criteria andPatientidNotEqualTo(Long value) {
            addCriterion("PATIENTID <>", value, "patientid");
            return (Criteria) this;
        }

        public Criteria andPatientidGreaterThan(Long value) {
            addCriterion("PATIENTID >", value, "patientid");
            return (Criteria) this;
        }

        public Criteria andPatientidGreaterThanOrEqualTo(Long value) {
            addCriterion("PATIENTID >=", value, "patientid");
            return (Criteria) this;
        }

        public Criteria andPatientidLessThan(Long value) {
            addCriterion("PATIENTID <", value, "patientid");
            return (Criteria) this;
        }

        public Criteria andPatientidLessThanOrEqualTo(Long value) {
            addCriterion("PATIENTID <=", value, "patientid");
            return (Criteria) this;
        }

        public Criteria andPatientidIn(List<Long> values) {
            addCriterion("PATIENTID in", values, "patientid");
            return (Criteria) this;
        }

        public Criteria andPatientidNotIn(List<Long> values) {
            addCriterion("PATIENTID not in", values, "patientid");
            return (Criteria) this;
        }

        public Criteria andPatientidBetween(Long value1, Long value2) {
            addCriterion("PATIENTID between", value1, value2, "patientid");
            return (Criteria) this;
        }

        public Criteria andPatientidNotBetween(Long value1, Long value2) {
            addCriterion("PATIENTID not between", value1, value2, "patientid");
            return (Criteria) this;
        }

        public Criteria andMrnIsNull() {
            addCriterion("MRN is null");
            return (Criteria) this;
        }

        public Criteria andMrnIsNotNull() {
            addCriterion("MRN is not null");
            return (Criteria) this;
        }

        public Criteria andMrnEqualTo(String value) {
            addCriterion("MRN =", value, "mrn");
            return (Criteria) this;
        }

        public Criteria andMrnNotEqualTo(String value) {
            addCriterion("MRN <>", value, "mrn");
            return (Criteria) this;
        }

        public Criteria andMrnGreaterThan(String value) {
            addCriterion("MRN >", value, "mrn");
            return (Criteria) this;
        }

        public Criteria andMrnGreaterThanOrEqualTo(String value) {
            addCriterion("MRN >=", value, "mrn");
            return (Criteria) this;
        }

        public Criteria andMrnLessThan(String value) {
            addCriterion("MRN <", value, "mrn");
            return (Criteria) this;
        }

        public Criteria andMrnLessThanOrEqualTo(String value) {
            addCriterion("MRN <=", value, "mrn");
            return (Criteria) this;
        }

        public Criteria andMrnLike(String value) {
            addCriterion("MRN like", value, "mrn");
            return (Criteria) this;
        }

        public Criteria andMrnNotLike(String value) {
            addCriterion("MRN not like", value, "mrn");
            return (Criteria) this;
        }

        public Criteria andMrnIn(List<String> values) {
            addCriterion("MRN in", values, "mrn");
            return (Criteria) this;
        }

        public Criteria andMrnNotIn(List<String> values) {
            addCriterion("MRN not in", values, "mrn");
            return (Criteria) this;
        }

        public Criteria andMrnBetween(String value1, String value2) {
            addCriterion("MRN between", value1, value2, "mrn");
            return (Criteria) this;
        }

        public Criteria andMrnNotBetween(String value1, String value2) {
            addCriterion("MRN not between", value1, value2, "mrn");
            return (Criteria) this;
        }

        public Criteria andLastNameIsNull() {
            addCriterion("LAST_NAME is null");
            return (Criteria) this;
        }

        public Criteria andLastNameIsNotNull() {
            addCriterion("LAST_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andLastNameEqualTo(String value) {
            addCriterion("LAST_NAME =", value, "lastName");
            return (Criteria) this;
        }

        public Criteria andLastNameNotEqualTo(String value) {
            addCriterion("LAST_NAME <>", value, "lastName");
            return (Criteria) this;
        }

        public Criteria andLastNameGreaterThan(String value) {
            addCriterion("LAST_NAME >", value, "lastName");
            return (Criteria) this;
        }

        public Criteria andLastNameGreaterThanOrEqualTo(String value) {
            addCriterion("LAST_NAME >=", value, "lastName");
            return (Criteria) this;
        }

        public Criteria andLastNameLessThan(String value) {
            addCriterion("LAST_NAME <", value, "lastName");
            return (Criteria) this;
        }

        public Criteria andLastNameLessThanOrEqualTo(String value) {
            addCriterion("LAST_NAME <=", value, "lastName");
            return (Criteria) this;
        }

        public Criteria andLastNameLike(String value) {
            addCriterion("LAST_NAME like", value, "lastName");
            return (Criteria) this;
        }

        public Criteria andLastNameNotLike(String value) {
            addCriterion("LAST_NAME not like", value, "lastName");
            return (Criteria) this;
        }

        public Criteria andLastNameIn(List<String> values) {
            addCriterion("LAST_NAME in", values, "lastName");
            return (Criteria) this;
        }

        public Criteria andLastNameNotIn(List<String> values) {
            addCriterion("LAST_NAME not in", values, "lastName");
            return (Criteria) this;
        }

        public Criteria andLastNameBetween(String value1, String value2) {
            addCriterion("LAST_NAME between", value1, value2, "lastName");
            return (Criteria) this;
        }

        public Criteria andLastNameNotBetween(String value1, String value2) {
            addCriterion("LAST_NAME not between", value1, value2, "lastName");
            return (Criteria) this;
        }

        public Criteria andFirstNameIsNull() {
            addCriterion("FIRST_NAME is null");
            return (Criteria) this;
        }

        public Criteria andFirstNameIsNotNull() {
            addCriterion("FIRST_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andFirstNameEqualTo(String value) {
            addCriterion("FIRST_NAME =", value, "firstName");
            return (Criteria) this;
        }

        public Criteria andFirstNameNotEqualTo(String value) {
            addCriterion("FIRST_NAME <>", value, "firstName");
            return (Criteria) this;
        }

        public Criteria andFirstNameGreaterThan(String value) {
            addCriterion("FIRST_NAME >", value, "firstName");
            return (Criteria) this;
        }

        public Criteria andFirstNameGreaterThanOrEqualTo(String value) {
            addCriterion("FIRST_NAME >=", value, "firstName");
            return (Criteria) this;
        }

        public Criteria andFirstNameLessThan(String value) {
            addCriterion("FIRST_NAME <", value, "firstName");
            return (Criteria) this;
        }

        public Criteria andFirstNameLessThanOrEqualTo(String value) {
            addCriterion("FIRST_NAME <=", value, "firstName");
            return (Criteria) this;
        }

        public Criteria andFirstNameLike(String value) {
            addCriterion("FIRST_NAME like", value, "firstName");
            return (Criteria) this;
        }

        public Criteria andFirstNameNotLike(String value) {
            addCriterion("FIRST_NAME not like", value, "firstName");
            return (Criteria) this;
        }

        public Criteria andFirstNameIn(List<String> values) {
            addCriterion("FIRST_NAME in", values, "firstName");
            return (Criteria) this;
        }

        public Criteria andFirstNameNotIn(List<String> values) {
            addCriterion("FIRST_NAME not in", values, "firstName");
            return (Criteria) this;
        }

        public Criteria andFirstNameBetween(String value1, String value2) {
            addCriterion("FIRST_NAME between", value1, value2, "firstName");
            return (Criteria) this;
        }

        public Criteria andFirstNameNotBetween(String value1, String value2) {
            addCriterion("FIRST_NAME not between", value1, value2, "firstName");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("PHONE is null");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("PHONE is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneEqualTo(String value) {
            addCriterion("PHONE =", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotEqualTo(String value) {
            addCriterion("PHONE <>", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThan(String value) {
            addCriterion("PHONE >", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("PHONE >=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThan(String value) {
            addCriterion("PHONE <", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThanOrEqualTo(String value) {
            addCriterion("PHONE <=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLike(String value) {
            addCriterion("PHONE like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotLike(String value) {
            addCriterion("PHONE not like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneIn(List<String> values) {
            addCriterion("PHONE in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotIn(List<String> values) {
            addCriterion("PHONE not in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneBetween(String value1, String value2) {
            addCriterion("PHONE between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotBetween(String value1, String value2) {
            addCriterion("PHONE not between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andGenderIsNull() {
            addCriterion("GENDER is null");
            return (Criteria) this;
        }

        public Criteria andGenderIsNotNull() {
            addCriterion("GENDER is not null");
            return (Criteria) this;
        }

        public Criteria andGenderEqualTo(String value) {
            addCriterion("GENDER =", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotEqualTo(String value) {
            addCriterion("GENDER <>", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThan(String value) {
            addCriterion("GENDER >", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThanOrEqualTo(String value) {
            addCriterion("GENDER >=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThan(String value) {
            addCriterion("GENDER <", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThanOrEqualTo(String value) {
            addCriterion("GENDER <=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLike(String value) {
            addCriterion("GENDER like", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotLike(String value) {
            addCriterion("GENDER not like", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderIn(List<String> values) {
            addCriterion("GENDER in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotIn(List<String> values) {
            addCriterion("GENDER not in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderBetween(String value1, String value2) {
            addCriterion("GENDER between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotBetween(String value1, String value2) {
            addCriterion("GENDER not between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andDobIsNull() {
            addCriterion("DOB is null");
            return (Criteria) this;
        }

        public Criteria andDobIsNotNull() {
            addCriterion("DOB is not null");
            return (Criteria) this;
        }

        public Criteria andDobEqualTo(Date value) {
            addCriterionForJDBCDate("DOB =", value, "dob");
            return (Criteria) this;
        }

        public Criteria andDobNotEqualTo(Date value) {
            addCriterionForJDBCDate("DOB <>", value, "dob");
            return (Criteria) this;
        }

        public Criteria andDobGreaterThan(Date value) {
            addCriterionForJDBCDate("DOB >", value, "dob");
            return (Criteria) this;
        }

        public Criteria andDobGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("DOB >=", value, "dob");
            return (Criteria) this;
        }

        public Criteria andDobLessThan(Date value) {
            addCriterionForJDBCDate("DOB <", value, "dob");
            return (Criteria) this;
        }

        public Criteria andDobLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("DOB <=", value, "dob");
            return (Criteria) this;
        }

        public Criteria andDobIn(List<Date> values) {
            addCriterionForJDBCDate("DOB in", values, "dob");
            return (Criteria) this;
        }

        public Criteria andDobNotIn(List<Date> values) {
            addCriterionForJDBCDate("DOB not in", values, "dob");
            return (Criteria) this;
        }

        public Criteria andDobBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("DOB between", value1, value2, "dob");
            return (Criteria) this;
        }

        public Criteria andDobNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("DOB not between", value1, value2, "dob");
            return (Criteria) this;
        }

        public Criteria andEthnicityIsNull() {
            addCriterion("ETHNICITY is null");
            return (Criteria) this;
        }

        public Criteria andEthnicityIsNotNull() {
            addCriterion("ETHNICITY is not null");
            return (Criteria) this;
        }

        public Criteria andEthnicityEqualTo(String value) {
            addCriterion("ETHNICITY =", value, "ethnicity");
            return (Criteria) this;
        }

        public Criteria andEthnicityNotEqualTo(String value) {
            addCriterion("ETHNICITY <>", value, "ethnicity");
            return (Criteria) this;
        }

        public Criteria andEthnicityGreaterThan(String value) {
            addCriterion("ETHNICITY >", value, "ethnicity");
            return (Criteria) this;
        }

        public Criteria andEthnicityGreaterThanOrEqualTo(String value) {
            addCriterion("ETHNICITY >=", value, "ethnicity");
            return (Criteria) this;
        }

        public Criteria andEthnicityLessThan(String value) {
            addCriterion("ETHNICITY <", value, "ethnicity");
            return (Criteria) this;
        }

        public Criteria andEthnicityLessThanOrEqualTo(String value) {
            addCriterion("ETHNICITY <=", value, "ethnicity");
            return (Criteria) this;
        }

        public Criteria andEthnicityLike(String value) {
            addCriterion("ETHNICITY like", value, "ethnicity");
            return (Criteria) this;
        }

        public Criteria andEthnicityNotLike(String value) {
            addCriterion("ETHNICITY not like", value, "ethnicity");
            return (Criteria) this;
        }

        public Criteria andEthnicityIn(List<String> values) {
            addCriterion("ETHNICITY in", values, "ethnicity");
            return (Criteria) this;
        }

        public Criteria andEthnicityNotIn(List<String> values) {
            addCriterion("ETHNICITY not in", values, "ethnicity");
            return (Criteria) this;
        }

        public Criteria andEthnicityBetween(String value1, String value2) {
            addCriterion("ETHNICITY between", value1, value2, "ethnicity");
            return (Criteria) this;
        }

        public Criteria andEthnicityNotBetween(String value1, String value2) {
            addCriterion("ETHNICITY not between", value1, value2, "ethnicity");
            return (Criteria) this;
        }

        public Criteria andRaceIsNull() {
            addCriterion("RACE is null");
            return (Criteria) this;
        }

        public Criteria andRaceIsNotNull() {
            addCriterion("RACE is not null");
            return (Criteria) this;
        }

        public Criteria andRaceEqualTo(String value) {
            addCriterion("RACE =", value, "race");
            return (Criteria) this;
        }

        public Criteria andRaceNotEqualTo(String value) {
            addCriterion("RACE <>", value, "race");
            return (Criteria) this;
        }

        public Criteria andRaceGreaterThan(String value) {
            addCriterion("RACE >", value, "race");
            return (Criteria) this;
        }

        public Criteria andRaceGreaterThanOrEqualTo(String value) {
            addCriterion("RACE >=", value, "race");
            return (Criteria) this;
        }

        public Criteria andRaceLessThan(String value) {
            addCriterion("RACE <", value, "race");
            return (Criteria) this;
        }

        public Criteria andRaceLessThanOrEqualTo(String value) {
            addCriterion("RACE <=", value, "race");
            return (Criteria) this;
        }

        public Criteria andRaceLike(String value) {
            addCriterion("RACE like", value, "race");
            return (Criteria) this;
        }

        public Criteria andRaceNotLike(String value) {
            addCriterion("RACE not like", value, "race");
            return (Criteria) this;
        }

        public Criteria andRaceIn(List<String> values) {
            addCriterion("RACE in", values, "race");
            return (Criteria) this;
        }

        public Criteria andRaceNotIn(List<String> values) {
            addCriterion("RACE not in", values, "race");
            return (Criteria) this;
        }

        public Criteria andRaceBetween(String value1, String value2) {
            addCriterion("RACE between", value1, value2, "race");
            return (Criteria) this;
        }

        public Criteria andRaceNotBetween(String value1, String value2) {
            addCriterion("RACE not between", value1, value2, "race");
            return (Criteria) this;
        }

        public Criteria andStreetAddress1IsNull() {
            addCriterion("STREET_ADDRESS_1 is null");
            return (Criteria) this;
        }

        public Criteria andStreetAddress1IsNotNull() {
            addCriterion("STREET_ADDRESS_1 is not null");
            return (Criteria) this;
        }

        public Criteria andStreetAddress1EqualTo(String value) {
            addCriterion("STREET_ADDRESS_1 =", value, "streetAddress1");
            return (Criteria) this;
        }

        public Criteria andStreetAddress1NotEqualTo(String value) {
            addCriterion("STREET_ADDRESS_1 <>", value, "streetAddress1");
            return (Criteria) this;
        }

        public Criteria andStreetAddress1GreaterThan(String value) {
            addCriterion("STREET_ADDRESS_1 >", value, "streetAddress1");
            return (Criteria) this;
        }

        public Criteria andStreetAddress1GreaterThanOrEqualTo(String value) {
            addCriterion("STREET_ADDRESS_1 >=", value, "streetAddress1");
            return (Criteria) this;
        }

        public Criteria andStreetAddress1LessThan(String value) {
            addCriterion("STREET_ADDRESS_1 <", value, "streetAddress1");
            return (Criteria) this;
        }

        public Criteria andStreetAddress1LessThanOrEqualTo(String value) {
            addCriterion("STREET_ADDRESS_1 <=", value, "streetAddress1");
            return (Criteria) this;
        }

        public Criteria andStreetAddress1Like(String value) {
            addCriterion("STREET_ADDRESS_1 like", value, "streetAddress1");
            return (Criteria) this;
        }

        public Criteria andStreetAddress1NotLike(String value) {
            addCriterion("STREET_ADDRESS_1 not like", value, "streetAddress1");
            return (Criteria) this;
        }

        public Criteria andStreetAddress1In(List<String> values) {
            addCriterion("STREET_ADDRESS_1 in", values, "streetAddress1");
            return (Criteria) this;
        }

        public Criteria andStreetAddress1NotIn(List<String> values) {
            addCriterion("STREET_ADDRESS_1 not in", values, "streetAddress1");
            return (Criteria) this;
        }

        public Criteria andStreetAddress1Between(String value1, String value2) {
            addCriterion("STREET_ADDRESS_1 between", value1, value2, "streetAddress1");
            return (Criteria) this;
        }

        public Criteria andStreetAddress1NotBetween(String value1, String value2) {
            addCriterion("STREET_ADDRESS_1 not between", value1, value2, "streetAddress1");
            return (Criteria) this;
        }

        public Criteria andStreetAddress2IsNull() {
            addCriterion("STREET_ADDRESS_2 is null");
            return (Criteria) this;
        }

        public Criteria andStreetAddress2IsNotNull() {
            addCriterion("STREET_ADDRESS_2 is not null");
            return (Criteria) this;
        }

        public Criteria andStreetAddress2EqualTo(String value) {
            addCriterion("STREET_ADDRESS_2 =", value, "streetAddress2");
            return (Criteria) this;
        }

        public Criteria andStreetAddress2NotEqualTo(String value) {
            addCriterion("STREET_ADDRESS_2 <>", value, "streetAddress2");
            return (Criteria) this;
        }

        public Criteria andStreetAddress2GreaterThan(String value) {
            addCriterion("STREET_ADDRESS_2 >", value, "streetAddress2");
            return (Criteria) this;
        }

        public Criteria andStreetAddress2GreaterThanOrEqualTo(String value) {
            addCriterion("STREET_ADDRESS_2 >=", value, "streetAddress2");
            return (Criteria) this;
        }

        public Criteria andStreetAddress2LessThan(String value) {
            addCriterion("STREET_ADDRESS_2 <", value, "streetAddress2");
            return (Criteria) this;
        }

        public Criteria andStreetAddress2LessThanOrEqualTo(String value) {
            addCriterion("STREET_ADDRESS_2 <=", value, "streetAddress2");
            return (Criteria) this;
        }

        public Criteria andStreetAddress2Like(String value) {
            addCriterion("STREET_ADDRESS_2 like", value, "streetAddress2");
            return (Criteria) this;
        }

        public Criteria andStreetAddress2NotLike(String value) {
            addCriterion("STREET_ADDRESS_2 not like", value, "streetAddress2");
            return (Criteria) this;
        }

        public Criteria andStreetAddress2In(List<String> values) {
            addCriterion("STREET_ADDRESS_2 in", values, "streetAddress2");
            return (Criteria) this;
        }

        public Criteria andStreetAddress2NotIn(List<String> values) {
            addCriterion("STREET_ADDRESS_2 not in", values, "streetAddress2");
            return (Criteria) this;
        }

        public Criteria andStreetAddress2Between(String value1, String value2) {
            addCriterion("STREET_ADDRESS_2 between", value1, value2, "streetAddress2");
            return (Criteria) this;
        }

        public Criteria andStreetAddress2NotBetween(String value1, String value2) {
            addCriterion("STREET_ADDRESS_2 not between", value1, value2, "streetAddress2");
            return (Criteria) this;
        }

        public Criteria andCityIsNull() {
            addCriterion("CITY is null");
            return (Criteria) this;
        }

        public Criteria andCityIsNotNull() {
            addCriterion("CITY is not null");
            return (Criteria) this;
        }

        public Criteria andCityEqualTo(String value) {
            addCriterion("CITY =", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotEqualTo(String value) {
            addCriterion("CITY <>", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThan(String value) {
            addCriterion("CITY >", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThanOrEqualTo(String value) {
            addCriterion("CITY >=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThan(String value) {
            addCriterion("CITY <", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThanOrEqualTo(String value) {
            addCriterion("CITY <=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLike(String value) {
            addCriterion("CITY like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotLike(String value) {
            addCriterion("CITY not like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityIn(List<String> values) {
            addCriterion("CITY in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotIn(List<String> values) {
            addCriterion("CITY not in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityBetween(String value1, String value2) {
            addCriterion("CITY between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotBetween(String value1, String value2) {
            addCriterion("CITY not between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andStateCdIsNull() {
            addCriterion("STATE_CD is null");
            return (Criteria) this;
        }

        public Criteria andStateCdIsNotNull() {
            addCriterion("STATE_CD is not null");
            return (Criteria) this;
        }

        public Criteria andStateCdEqualTo(String value) {
            addCriterion("STATE_CD =", value, "stateCd");
            return (Criteria) this;
        }

        public Criteria andStateCdNotEqualTo(String value) {
            addCriterion("STATE_CD <>", value, "stateCd");
            return (Criteria) this;
        }

        public Criteria andStateCdGreaterThan(String value) {
            addCriterion("STATE_CD >", value, "stateCd");
            return (Criteria) this;
        }

        public Criteria andStateCdGreaterThanOrEqualTo(String value) {
            addCriterion("STATE_CD >=", value, "stateCd");
            return (Criteria) this;
        }

        public Criteria andStateCdLessThan(String value) {
            addCriterion("STATE_CD <", value, "stateCd");
            return (Criteria) this;
        }

        public Criteria andStateCdLessThanOrEqualTo(String value) {
            addCriterion("STATE_CD <=", value, "stateCd");
            return (Criteria) this;
        }

        public Criteria andStateCdLike(String value) {
            addCriterion("STATE_CD like", value, "stateCd");
            return (Criteria) this;
        }

        public Criteria andStateCdNotLike(String value) {
            addCriterion("STATE_CD not like", value, "stateCd");
            return (Criteria) this;
        }

        public Criteria andStateCdIn(List<String> values) {
            addCriterion("STATE_CD in", values, "stateCd");
            return (Criteria) this;
        }

        public Criteria andStateCdNotIn(List<String> values) {
            addCriterion("STATE_CD not in", values, "stateCd");
            return (Criteria) this;
        }

        public Criteria andStateCdBetween(String value1, String value2) {
            addCriterion("STATE_CD between", value1, value2, "stateCd");
            return (Criteria) this;
        }

        public Criteria andStateCdNotBetween(String value1, String value2) {
            addCriterion("STATE_CD not between", value1, value2, "stateCd");
            return (Criteria) this;
        }

        public Criteria andZipIsNull() {
            addCriterion("ZIP is null");
            return (Criteria) this;
        }

        public Criteria andZipIsNotNull() {
            addCriterion("ZIP is not null");
            return (Criteria) this;
        }

        public Criteria andZipEqualTo(String value) {
            addCriterion("ZIP =", value, "zip");
            return (Criteria) this;
        }

        public Criteria andZipNotEqualTo(String value) {
            addCriterion("ZIP <>", value, "zip");
            return (Criteria) this;
        }

        public Criteria andZipGreaterThan(String value) {
            addCriterion("ZIP >", value, "zip");
            return (Criteria) this;
        }

        public Criteria andZipGreaterThanOrEqualTo(String value) {
            addCriterion("ZIP >=", value, "zip");
            return (Criteria) this;
        }

        public Criteria andZipLessThan(String value) {
            addCriterion("ZIP <", value, "zip");
            return (Criteria) this;
        }

        public Criteria andZipLessThanOrEqualTo(String value) {
            addCriterion("ZIP <=", value, "zip");
            return (Criteria) this;
        }

        public Criteria andZipLike(String value) {
            addCriterion("ZIP like", value, "zip");
            return (Criteria) this;
        }

        public Criteria andZipNotLike(String value) {
            addCriterion("ZIP not like", value, "zip");
            return (Criteria) this;
        }

        public Criteria andZipIn(List<String> values) {
            addCriterion("ZIP in", values, "zip");
            return (Criteria) this;
        }

        public Criteria andZipNotIn(List<String> values) {
            addCriterion("ZIP not in", values, "zip");
            return (Criteria) this;
        }

        public Criteria andZipBetween(String value1, String value2) {
            addCriterion("ZIP between", value1, value2, "zip");
            return (Criteria) this;
        }

        public Criteria andZipNotBetween(String value1, String value2) {
            addCriterion("ZIP not between", value1, value2, "zip");
            return (Criteria) this;
        }

        public Criteria andAltPhoneIsNull() {
            addCriterion("ALT_PHONE is null");
            return (Criteria) this;
        }

        public Criteria andAltPhoneIsNotNull() {
            addCriterion("ALT_PHONE is not null");
            return (Criteria) this;
        }

        public Criteria andAltPhoneEqualTo(String value) {
            addCriterion("ALT_PHONE =", value, "altPhone");
            return (Criteria) this;
        }

        public Criteria andAltPhoneNotEqualTo(String value) {
            addCriterion("ALT_PHONE <>", value, "altPhone");
            return (Criteria) this;
        }

        public Criteria andAltPhoneGreaterThan(String value) {
            addCriterion("ALT_PHONE >", value, "altPhone");
            return (Criteria) this;
        }

        public Criteria andAltPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("ALT_PHONE >=", value, "altPhone");
            return (Criteria) this;
        }

        public Criteria andAltPhoneLessThan(String value) {
            addCriterion("ALT_PHONE <", value, "altPhone");
            return (Criteria) this;
        }

        public Criteria andAltPhoneLessThanOrEqualTo(String value) {
            addCriterion("ALT_PHONE <=", value, "altPhone");
            return (Criteria) this;
        }

        public Criteria andAltPhoneLike(String value) {
            addCriterion("ALT_PHONE like", value, "altPhone");
            return (Criteria) this;
        }

        public Criteria andAltPhoneNotLike(String value) {
            addCriterion("ALT_PHONE not like", value, "altPhone");
            return (Criteria) this;
        }

        public Criteria andAltPhoneIn(List<String> values) {
            addCriterion("ALT_PHONE in", values, "altPhone");
            return (Criteria) this;
        }

        public Criteria andAltPhoneNotIn(List<String> values) {
            addCriterion("ALT_PHONE not in", values, "altPhone");
            return (Criteria) this;
        }

        public Criteria andAltPhoneBetween(String value1, String value2) {
            addCriterion("ALT_PHONE between", value1, value2, "altPhone");
            return (Criteria) this;
        }

        public Criteria andAltPhoneNotBetween(String value1, String value2) {
            addCriterion("ALT_PHONE not between", value1, value2, "altPhone");
            return (Criteria) this;
        }

        public Criteria andSalutationIsNull() {
            addCriterion("SALUTATION is null");
            return (Criteria) this;
        }

        public Criteria andSalutationIsNotNull() {
            addCriterion("SALUTATION is not null");
            return (Criteria) this;
        }

        public Criteria andSalutationEqualTo(String value) {
            addCriterion("SALUTATION =", value, "salutation");
            return (Criteria) this;
        }

        public Criteria andSalutationNotEqualTo(String value) {
            addCriterion("SALUTATION <>", value, "salutation");
            return (Criteria) this;
        }

        public Criteria andSalutationGreaterThan(String value) {
            addCriterion("SALUTATION >", value, "salutation");
            return (Criteria) this;
        }

        public Criteria andSalutationGreaterThanOrEqualTo(String value) {
            addCriterion("SALUTATION >=", value, "salutation");
            return (Criteria) this;
        }

        public Criteria andSalutationLessThan(String value) {
            addCriterion("SALUTATION <", value, "salutation");
            return (Criteria) this;
        }

        public Criteria andSalutationLessThanOrEqualTo(String value) {
            addCriterion("SALUTATION <=", value, "salutation");
            return (Criteria) this;
        }

        public Criteria andSalutationLike(String value) {
            addCriterion("SALUTATION like", value, "salutation");
            return (Criteria) this;
        }

        public Criteria andSalutationNotLike(String value) {
            addCriterion("SALUTATION not like", value, "salutation");
            return (Criteria) this;
        }

        public Criteria andSalutationIn(List<String> values) {
            addCriterion("SALUTATION in", values, "salutation");
            return (Criteria) this;
        }

        public Criteria andSalutationNotIn(List<String> values) {
            addCriterion("SALUTATION not in", values, "salutation");
            return (Criteria) this;
        }

        public Criteria andSalutationBetween(String value1, String value2) {
            addCriterion("SALUTATION between", value1, value2, "salutation");
            return (Criteria) this;
        }

        public Criteria andSalutationNotBetween(String value1, String value2) {
            addCriterion("SALUTATION not between", value1, value2, "salutation");
            return (Criteria) this;
        }

        public Criteria andCountryIsNull() {
            addCriterion("COUNTRY is null");
            return (Criteria) this;
        }

        public Criteria andCountryIsNotNull() {
            addCriterion("COUNTRY is not null");
            return (Criteria) this;
        }

        public Criteria andCountryEqualTo(String value) {
            addCriterion("COUNTRY =", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotEqualTo(String value) {
            addCriterion("COUNTRY <>", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryGreaterThan(String value) {
            addCriterion("COUNTRY >", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryGreaterThanOrEqualTo(String value) {
            addCriterion("COUNTRY >=", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLessThan(String value) {
            addCriterion("COUNTRY <", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLessThanOrEqualTo(String value) {
            addCriterion("COUNTRY <=", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLike(String value) {
            addCriterion("COUNTRY like", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotLike(String value) {
            addCriterion("COUNTRY not like", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryIn(List<String> values) {
            addCriterion("COUNTRY in", values, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotIn(List<String> values) {
            addCriterion("COUNTRY not in", values, "country");
            return (Criteria) this;
        }

        public Criteria andCountryBetween(String value1, String value2) {
            addCriterion("COUNTRY between", value1, value2, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotBetween(String value1, String value2) {
            addCriterion("COUNTRY not between", value1, value2, "country");
            return (Criteria) this;
        }

        public Criteria andNoteIsNull() {
            addCriterion("NOTE is null");
            return (Criteria) this;
        }

        public Criteria andNoteIsNotNull() {
            addCriterion("NOTE is not null");
            return (Criteria) this;
        }

        public Criteria andNoteEqualTo(String value) {
            addCriterion("NOTE =", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotEqualTo(String value) {
            addCriterion("NOTE <>", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThan(String value) {
            addCriterion("NOTE >", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThanOrEqualTo(String value) {
            addCriterion("NOTE >=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThan(String value) {
            addCriterion("NOTE <", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThanOrEqualTo(String value) {
            addCriterion("NOTE <=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLike(String value) {
            addCriterion("NOTE like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotLike(String value) {
            addCriterion("NOTE not like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteIn(List<String> values) {
            addCriterion("NOTE in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotIn(List<String> values) {
            addCriterion("NOTE not in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteBetween(String value1, String value2) {
            addCriterion("NOTE between", value1, value2, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotBetween(String value1, String value2) {
            addCriterion("NOTE not between", value1, value2, "note");
            return (Criteria) this;
        }

        public Criteria andAuthkeyIsNull() {
            addCriterion("AUTHKEY is null");
            return (Criteria) this;
        }

        public Criteria andAuthkeyIsNotNull() {
            addCriterion("AUTHKEY is not null");
            return (Criteria) this;
        }

        public Criteria andAuthkeyEqualTo(String value) {
            addCriterion("AUTHKEY =", value, "authkey");
            return (Criteria) this;
        }

        public Criteria andAuthkeyNotEqualTo(String value) {
            addCriterion("AUTHKEY <>", value, "authkey");
            return (Criteria) this;
        }

        public Criteria andAuthkeyGreaterThan(String value) {
            addCriterion("AUTHKEY >", value, "authkey");
            return (Criteria) this;
        }

        public Criteria andAuthkeyGreaterThanOrEqualTo(String value) {
            addCriterion("AUTHKEY >=", value, "authkey");
            return (Criteria) this;
        }

        public Criteria andAuthkeyLessThan(String value) {
            addCriterion("AUTHKEY <", value, "authkey");
            return (Criteria) this;
        }

        public Criteria andAuthkeyLessThanOrEqualTo(String value) {
            addCriterion("AUTHKEY <=", value, "authkey");
            return (Criteria) this;
        }

        public Criteria andAuthkeyLike(String value) {
            addCriterion("AUTHKEY like", value, "authkey");
            return (Criteria) this;
        }

        public Criteria andAuthkeyNotLike(String value) {
            addCriterion("AUTHKEY not like", value, "authkey");
            return (Criteria) this;
        }

        public Criteria andAuthkeyIn(List<String> values) {
            addCriterion("AUTHKEY in", values, "authkey");
            return (Criteria) this;
        }

        public Criteria andAuthkeyNotIn(List<String> values) {
            addCriterion("AUTHKEY not in", values, "authkey");
            return (Criteria) this;
        }

        public Criteria andAuthkeyBetween(String value1, String value2) {
            addCriterion("AUTHKEY between", value1, value2, "authkey");
            return (Criteria) this;
        }

        public Criteria andAuthkeyNotBetween(String value1, String value2) {
            addCriterion("AUTHKEY not between", value1, value2, "authkey");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("USERNAME is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("USERNAME is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("USERNAME =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("USERNAME <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("USERNAME >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("USERNAME >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("USERNAME <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("USERNAME <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("USERNAME like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("USERNAME not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("USERNAME in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("USERNAME not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("USERNAME between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("USERNAME not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andSystemaccessIsNull() {
            addCriterion("SYSTEMACCESS is null");
            return (Criteria) this;
        }

        public Criteria andSystemaccessIsNotNull() {
            addCriterion("SYSTEMACCESS is not null");
            return (Criteria) this;
        }

        public Criteria andSystemaccessEqualTo(String value) {
            addCriterion("SYSTEMACCESS =", value, "systemaccess");
            return (Criteria) this;
        }

        public Criteria andSystemaccessNotEqualTo(String value) {
            addCriterion("SYSTEMACCESS <>", value, "systemaccess");
            return (Criteria) this;
        }

        public Criteria andSystemaccessGreaterThan(String value) {
            addCriterion("SYSTEMACCESS >", value, "systemaccess");
            return (Criteria) this;
        }

        public Criteria andSystemaccessGreaterThanOrEqualTo(String value) {
            addCriterion("SYSTEMACCESS >=", value, "systemaccess");
            return (Criteria) this;
        }

        public Criteria andSystemaccessLessThan(String value) {
            addCriterion("SYSTEMACCESS <", value, "systemaccess");
            return (Criteria) this;
        }

        public Criteria andSystemaccessLessThanOrEqualTo(String value) {
            addCriterion("SYSTEMACCESS <=", value, "systemaccess");
            return (Criteria) this;
        }

        public Criteria andSystemaccessLike(String value) {
            addCriterion("SYSTEMACCESS like", value, "systemaccess");
            return (Criteria) this;
        }

        public Criteria andSystemaccessNotLike(String value) {
            addCriterion("SYSTEMACCESS not like", value, "systemaccess");
            return (Criteria) this;
        }

        public Criteria andSystemaccessIn(List<String> values) {
            addCriterion("SYSTEMACCESS in", values, "systemaccess");
            return (Criteria) this;
        }

        public Criteria andSystemaccessNotIn(List<String> values) {
            addCriterion("SYSTEMACCESS not in", values, "systemaccess");
            return (Criteria) this;
        }

        public Criteria andSystemaccessBetween(String value1, String value2) {
            addCriterion("SYSTEMACCESS between", value1, value2, "systemaccess");
            return (Criteria) this;
        }

        public Criteria andSystemaccessNotBetween(String value1, String value2) {
            addCriterion("SYSTEMACCESS not between", value1, value2, "systemaccess");
            return (Criteria) this;
        }

        public Criteria andHandnessIsNull() {
            addCriterion("HANDNESS is null");
            return (Criteria) this;
        }

        public Criteria andHandnessIsNotNull() {
            addCriterion("HANDNESS is not null");
            return (Criteria) this;
        }

        public Criteria andHandnessEqualTo(Short value) {
            addCriterion("HANDNESS =", value, "handness");
            return (Criteria) this;
        }

        public Criteria andHandnessNotEqualTo(Short value) {
            addCriterion("HANDNESS <>", value, "handness");
            return (Criteria) this;
        }

        public Criteria andHandnessGreaterThan(Short value) {
            addCriterion("HANDNESS >", value, "handness");
            return (Criteria) this;
        }

        public Criteria andHandnessGreaterThanOrEqualTo(Short value) {
            addCriterion("HANDNESS >=", value, "handness");
            return (Criteria) this;
        }

        public Criteria andHandnessLessThan(Short value) {
            addCriterion("HANDNESS <", value, "handness");
            return (Criteria) this;
        }

        public Criteria andHandnessLessThanOrEqualTo(Short value) {
            addCriterion("HANDNESS <=", value, "handness");
            return (Criteria) this;
        }

        public Criteria andHandnessIn(List<Short> values) {
            addCriterion("HANDNESS in", values, "handness");
            return (Criteria) this;
        }

        public Criteria andHandnessNotIn(List<Short> values) {
            addCriterion("HANDNESS not in", values, "handness");
            return (Criteria) this;
        }

        public Criteria andHandnessBetween(Short value1, Short value2) {
            addCriterion("HANDNESS between", value1, value2, "handness");
            return (Criteria) this;
        }

        public Criteria andHandnessNotBetween(Short value1, Short value2) {
            addCriterion("HANDNESS not between", value1, value2, "handness");
            return (Criteria) this;
        }

        public Criteria andOccupationIsNull() {
            addCriterion("OCCUPATION is null");
            return (Criteria) this;
        }

        public Criteria andOccupationIsNotNull() {
            addCriterion("OCCUPATION is not null");
            return (Criteria) this;
        }

        public Criteria andOccupationEqualTo(String value) {
            addCriterion("OCCUPATION =", value, "occupation");
            return (Criteria) this;
        }

        public Criteria andOccupationNotEqualTo(String value) {
            addCriterion("OCCUPATION <>", value, "occupation");
            return (Criteria) this;
        }

        public Criteria andOccupationGreaterThan(String value) {
            addCriterion("OCCUPATION >", value, "occupation");
            return (Criteria) this;
        }

        public Criteria andOccupationGreaterThanOrEqualTo(String value) {
            addCriterion("OCCUPATION >=", value, "occupation");
            return (Criteria) this;
        }

        public Criteria andOccupationLessThan(String value) {
            addCriterion("OCCUPATION <", value, "occupation");
            return (Criteria) this;
        }

        public Criteria andOccupationLessThanOrEqualTo(String value) {
            addCriterion("OCCUPATION <=", value, "occupation");
            return (Criteria) this;
        }

        public Criteria andOccupationLike(String value) {
            addCriterion("OCCUPATION like", value, "occupation");
            return (Criteria) this;
        }

        public Criteria andOccupationNotLike(String value) {
            addCriterion("OCCUPATION not like", value, "occupation");
            return (Criteria) this;
        }

        public Criteria andOccupationIn(List<String> values) {
            addCriterion("OCCUPATION in", values, "occupation");
            return (Criteria) this;
        }

        public Criteria andOccupationNotIn(List<String> values) {
            addCriterion("OCCUPATION not in", values, "occupation");
            return (Criteria) this;
        }

        public Criteria andOccupationBetween(String value1, String value2) {
            addCriterion("OCCUPATION between", value1, value2, "occupation");
            return (Criteria) this;
        }

        public Criteria andOccupationNotBetween(String value1, String value2) {
            addCriterion("OCCUPATION not between", value1, value2, "occupation");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PATIENT
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PATIENT
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}