package model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ProtocolExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PROTOCOL
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PROTOCOL
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PROTOCOL
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROTOCOL
     *
     * @mbggenerated
     */
    public ProtocolExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROTOCOL
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROTOCOL
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROTOCOL
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROTOCOL
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROTOCOL
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROTOCOL
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROTOCOL
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROTOCOL
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROTOCOL
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROTOCOL
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PROTOCOL
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDcpidIsNull() {
            addCriterion("DCPID is null");
            return (Criteria) this;
        }

        public Criteria andDcpidIsNotNull() {
            addCriterion("DCPID is not null");
            return (Criteria) this;
        }

        public Criteria andDcpidEqualTo(Long value) {
            addCriterion("DCPID =", value, "dcpid");
            return (Criteria) this;
        }

        public Criteria andDcpidNotEqualTo(Long value) {
            addCriterion("DCPID <>", value, "dcpid");
            return (Criteria) this;
        }

        public Criteria andDcpidGreaterThan(Long value) {
            addCriterion("DCPID >", value, "dcpid");
            return (Criteria) this;
        }

        public Criteria andDcpidGreaterThanOrEqualTo(Long value) {
            addCriterion("DCPID >=", value, "dcpid");
            return (Criteria) this;
        }

        public Criteria andDcpidLessThan(Long value) {
            addCriterion("DCPID <", value, "dcpid");
            return (Criteria) this;
        }

        public Criteria andDcpidLessThanOrEqualTo(Long value) {
            addCriterion("DCPID <=", value, "dcpid");
            return (Criteria) this;
        }

        public Criteria andDcpidIn(List<Long> values) {
            addCriterion("DCPID in", values, "dcpid");
            return (Criteria) this;
        }

        public Criteria andDcpidNotIn(List<Long> values) {
            addCriterion("DCPID not in", values, "dcpid");
            return (Criteria) this;
        }

        public Criteria andDcpidBetween(Long value1, Long value2) {
            addCriterion("DCPID between", value1, value2, "dcpid");
            return (Criteria) this;
        }

        public Criteria andDcpidNotBetween(Long value1, Long value2) {
            addCriterion("DCPID not between", value1, value2, "dcpid");
            return (Criteria) this;
        }

        public Criteria andProtocolnumIsNull() {
            addCriterion("PROTOCOLNUM is null");
            return (Criteria) this;
        }

        public Criteria andProtocolnumIsNotNull() {
            addCriterion("PROTOCOLNUM is not null");
            return (Criteria) this;
        }

        public Criteria andProtocolnumEqualTo(String value) {
            addCriterion("PROTOCOLNUM =", value, "protocolnum");
            return (Criteria) this;
        }

        public Criteria andProtocolnumNotEqualTo(String value) {
            addCriterion("PROTOCOLNUM <>", value, "protocolnum");
            return (Criteria) this;
        }

        public Criteria andProtocolnumGreaterThan(String value) {
            addCriterion("PROTOCOLNUM >", value, "protocolnum");
            return (Criteria) this;
        }

        public Criteria andProtocolnumGreaterThanOrEqualTo(String value) {
            addCriterion("PROTOCOLNUM >=", value, "protocolnum");
            return (Criteria) this;
        }

        public Criteria andProtocolnumLessThan(String value) {
            addCriterion("PROTOCOLNUM <", value, "protocolnum");
            return (Criteria) this;
        }

        public Criteria andProtocolnumLessThanOrEqualTo(String value) {
            addCriterion("PROTOCOLNUM <=", value, "protocolnum");
            return (Criteria) this;
        }

        public Criteria andProtocolnumLike(String value) {
            addCriterion("PROTOCOLNUM like", value, "protocolnum");
            return (Criteria) this;
        }

        public Criteria andProtocolnumNotLike(String value) {
            addCriterion("PROTOCOLNUM not like", value, "protocolnum");
            return (Criteria) this;
        }

        public Criteria andProtocolnumIn(List<String> values) {
            addCriterion("PROTOCOLNUM in", values, "protocolnum");
            return (Criteria) this;
        }

        public Criteria andProtocolnumNotIn(List<String> values) {
            addCriterion("PROTOCOLNUM not in", values, "protocolnum");
            return (Criteria) this;
        }

        public Criteria andProtocolnumBetween(String value1, String value2) {
            addCriterion("PROTOCOLNUM between", value1, value2, "protocolnum");
            return (Criteria) this;
        }

        public Criteria andProtocolnumNotBetween(String value1, String value2) {
            addCriterion("PROTOCOLNUM not between", value1, value2, "protocolnum");
            return (Criteria) this;
        }

        public Criteria andTempnumIsNull() {
            addCriterion("TEMPNUM is null");
            return (Criteria) this;
        }

        public Criteria andTempnumIsNotNull() {
            addCriterion("TEMPNUM is not null");
            return (Criteria) this;
        }

        public Criteria andTempnumEqualTo(String value) {
            addCriterion("TEMPNUM =", value, "tempnum");
            return (Criteria) this;
        }

        public Criteria andTempnumNotEqualTo(String value) {
            addCriterion("TEMPNUM <>", value, "tempnum");
            return (Criteria) this;
        }

        public Criteria andTempnumGreaterThan(String value) {
            addCriterion("TEMPNUM >", value, "tempnum");
            return (Criteria) this;
        }

        public Criteria andTempnumGreaterThanOrEqualTo(String value) {
            addCriterion("TEMPNUM >=", value, "tempnum");
            return (Criteria) this;
        }

        public Criteria andTempnumLessThan(String value) {
            addCriterion("TEMPNUM <", value, "tempnum");
            return (Criteria) this;
        }

        public Criteria andTempnumLessThanOrEqualTo(String value) {
            addCriterion("TEMPNUM <=", value, "tempnum");
            return (Criteria) this;
        }

        public Criteria andTempnumLike(String value) {
            addCriterion("TEMPNUM like", value, "tempnum");
            return (Criteria) this;
        }

        public Criteria andTempnumNotLike(String value) {
            addCriterion("TEMPNUM not like", value, "tempnum");
            return (Criteria) this;
        }

        public Criteria andTempnumIn(List<String> values) {
            addCriterion("TEMPNUM in", values, "tempnum");
            return (Criteria) this;
        }

        public Criteria andTempnumNotIn(List<String> values) {
            addCriterion("TEMPNUM not in", values, "tempnum");
            return (Criteria) this;
        }

        public Criteria andTempnumBetween(String value1, String value2) {
            addCriterion("TEMPNUM between", value1, value2, "tempnum");
            return (Criteria) this;
        }

        public Criteria andTempnumNotBetween(String value1, String value2) {
            addCriterion("TEMPNUM not between", value1, value2, "tempnum");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andInstituteIsNull() {
            addCriterion("INSTITUTE is null");
            return (Criteria) this;
        }

        public Criteria andInstituteIsNotNull() {
            addCriterion("INSTITUTE is not null");
            return (Criteria) this;
        }

        public Criteria andInstituteEqualTo(String value) {
            addCriterion("INSTITUTE =", value, "institute");
            return (Criteria) this;
        }

        public Criteria andInstituteNotEqualTo(String value) {
            addCriterion("INSTITUTE <>", value, "institute");
            return (Criteria) this;
        }

        public Criteria andInstituteGreaterThan(String value) {
            addCriterion("INSTITUTE >", value, "institute");
            return (Criteria) this;
        }

        public Criteria andInstituteGreaterThanOrEqualTo(String value) {
            addCriterion("INSTITUTE >=", value, "institute");
            return (Criteria) this;
        }

        public Criteria andInstituteLessThan(String value) {
            addCriterion("INSTITUTE <", value, "institute");
            return (Criteria) this;
        }

        public Criteria andInstituteLessThanOrEqualTo(String value) {
            addCriterion("INSTITUTE <=", value, "institute");
            return (Criteria) this;
        }

        public Criteria andInstituteLike(String value) {
            addCriterion("INSTITUTE like", value, "institute");
            return (Criteria) this;
        }

        public Criteria andInstituteNotLike(String value) {
            addCriterion("INSTITUTE not like", value, "institute");
            return (Criteria) this;
        }

        public Criteria andInstituteIn(List<String> values) {
            addCriterion("INSTITUTE in", values, "institute");
            return (Criteria) this;
        }

        public Criteria andInstituteNotIn(List<String> values) {
            addCriterion("INSTITUTE not in", values, "institute");
            return (Criteria) this;
        }

        public Criteria andInstituteBetween(String value1, String value2) {
            addCriterion("INSTITUTE between", value1, value2, "institute");
            return (Criteria) this;
        }

        public Criteria andInstituteNotBetween(String value1, String value2) {
            addCriterion("INSTITUTE not between", value1, value2, "institute");
            return (Criteria) this;
        }

        public Criteria andTechtxrnoteIsNull() {
            addCriterion("TECHTXRNOTE is null");
            return (Criteria) this;
        }

        public Criteria andTechtxrnoteIsNotNull() {
            addCriterion("TECHTXRNOTE is not null");
            return (Criteria) this;
        }

        public Criteria andTechtxrnoteEqualTo(String value) {
            addCriterion("TECHTXRNOTE =", value, "techtxrnote");
            return (Criteria) this;
        }

        public Criteria andTechtxrnoteNotEqualTo(String value) {
            addCriterion("TECHTXRNOTE <>", value, "techtxrnote");
            return (Criteria) this;
        }

        public Criteria andTechtxrnoteGreaterThan(String value) {
            addCriterion("TECHTXRNOTE >", value, "techtxrnote");
            return (Criteria) this;
        }

        public Criteria andTechtxrnoteGreaterThanOrEqualTo(String value) {
            addCriterion("TECHTXRNOTE >=", value, "techtxrnote");
            return (Criteria) this;
        }

        public Criteria andTechtxrnoteLessThan(String value) {
            addCriterion("TECHTXRNOTE <", value, "techtxrnote");
            return (Criteria) this;
        }

        public Criteria andTechtxrnoteLessThanOrEqualTo(String value) {
            addCriterion("TECHTXRNOTE <=", value, "techtxrnote");
            return (Criteria) this;
        }

        public Criteria andTechtxrnoteLike(String value) {
            addCriterion("TECHTXRNOTE like", value, "techtxrnote");
            return (Criteria) this;
        }

        public Criteria andTechtxrnoteNotLike(String value) {
            addCriterion("TECHTXRNOTE not like", value, "techtxrnote");
            return (Criteria) this;
        }

        public Criteria andTechtxrnoteIn(List<String> values) {
            addCriterion("TECHTXRNOTE in", values, "techtxrnote");
            return (Criteria) this;
        }

        public Criteria andTechtxrnoteNotIn(List<String> values) {
            addCriterion("TECHTXRNOTE not in", values, "techtxrnote");
            return (Criteria) this;
        }

        public Criteria andTechtxrnoteBetween(String value1, String value2) {
            addCriterion("TECHTXRNOTE between", value1, value2, "techtxrnote");
            return (Criteria) this;
        }

        public Criteria andTechtxrnoteNotBetween(String value1, String value2) {
            addCriterion("TECHTXRNOTE not between", value1, value2, "techtxrnote");
            return (Criteria) this;
        }

        public Criteria andAgreementnumIsNull() {
            addCriterion("AGREEMENTNUM is null");
            return (Criteria) this;
        }

        public Criteria andAgreementnumIsNotNull() {
            addCriterion("AGREEMENTNUM is not null");
            return (Criteria) this;
        }

        public Criteria andAgreementnumEqualTo(String value) {
            addCriterion("AGREEMENTNUM =", value, "agreementnum");
            return (Criteria) this;
        }

        public Criteria andAgreementnumNotEqualTo(String value) {
            addCriterion("AGREEMENTNUM <>", value, "agreementnum");
            return (Criteria) this;
        }

        public Criteria andAgreementnumGreaterThan(String value) {
            addCriterion("AGREEMENTNUM >", value, "agreementnum");
            return (Criteria) this;
        }

        public Criteria andAgreementnumGreaterThanOrEqualTo(String value) {
            addCriterion("AGREEMENTNUM >=", value, "agreementnum");
            return (Criteria) this;
        }

        public Criteria andAgreementnumLessThan(String value) {
            addCriterion("AGREEMENTNUM <", value, "agreementnum");
            return (Criteria) this;
        }

        public Criteria andAgreementnumLessThanOrEqualTo(String value) {
            addCriterion("AGREEMENTNUM <=", value, "agreementnum");
            return (Criteria) this;
        }

        public Criteria andAgreementnumLike(String value) {
            addCriterion("AGREEMENTNUM like", value, "agreementnum");
            return (Criteria) this;
        }

        public Criteria andAgreementnumNotLike(String value) {
            addCriterion("AGREEMENTNUM not like", value, "agreementnum");
            return (Criteria) this;
        }

        public Criteria andAgreementnumIn(List<String> values) {
            addCriterion("AGREEMENTNUM in", values, "agreementnum");
            return (Criteria) this;
        }

        public Criteria andAgreementnumNotIn(List<String> values) {
            addCriterion("AGREEMENTNUM not in", values, "agreementnum");
            return (Criteria) this;
        }

        public Criteria andAgreementnumBetween(String value1, String value2) {
            addCriterion("AGREEMENTNUM between", value1, value2, "agreementnum");
            return (Criteria) this;
        }

        public Criteria andAgreementnumNotBetween(String value1, String value2) {
            addCriterion("AGREEMENTNUM not between", value1, value2, "agreementnum");
            return (Criteria) this;
        }

        public Criteria andAgreementtypeIsNull() {
            addCriterion("AGREEMENTTYPE is null");
            return (Criteria) this;
        }

        public Criteria andAgreementtypeIsNotNull() {
            addCriterion("AGREEMENTTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andAgreementtypeEqualTo(String value) {
            addCriterion("AGREEMENTTYPE =", value, "agreementtype");
            return (Criteria) this;
        }

        public Criteria andAgreementtypeNotEqualTo(String value) {
            addCriterion("AGREEMENTTYPE <>", value, "agreementtype");
            return (Criteria) this;
        }

        public Criteria andAgreementtypeGreaterThan(String value) {
            addCriterion("AGREEMENTTYPE >", value, "agreementtype");
            return (Criteria) this;
        }

        public Criteria andAgreementtypeGreaterThanOrEqualTo(String value) {
            addCriterion("AGREEMENTTYPE >=", value, "agreementtype");
            return (Criteria) this;
        }

        public Criteria andAgreementtypeLessThan(String value) {
            addCriterion("AGREEMENTTYPE <", value, "agreementtype");
            return (Criteria) this;
        }

        public Criteria andAgreementtypeLessThanOrEqualTo(String value) {
            addCriterion("AGREEMENTTYPE <=", value, "agreementtype");
            return (Criteria) this;
        }

        public Criteria andAgreementtypeLike(String value) {
            addCriterion("AGREEMENTTYPE like", value, "agreementtype");
            return (Criteria) this;
        }

        public Criteria andAgreementtypeNotLike(String value) {
            addCriterion("AGREEMENTTYPE not like", value, "agreementtype");
            return (Criteria) this;
        }

        public Criteria andAgreementtypeIn(List<String> values) {
            addCriterion("AGREEMENTTYPE in", values, "agreementtype");
            return (Criteria) this;
        }

        public Criteria andAgreementtypeNotIn(List<String> values) {
            addCriterion("AGREEMENTTYPE not in", values, "agreementtype");
            return (Criteria) this;
        }

        public Criteria andAgreementtypeBetween(String value1, String value2) {
            addCriterion("AGREEMENTTYPE between", value1, value2, "agreementtype");
            return (Criteria) this;
        }

        public Criteria andAgreementtypeNotBetween(String value1, String value2) {
            addCriterion("AGREEMENTTYPE not between", value1, value2, "agreementtype");
            return (Criteria) this;
        }

        public Criteria andCreateyearIsNull() {
            addCriterion("CREATEYEAR is null");
            return (Criteria) this;
        }

        public Criteria andCreateyearIsNotNull() {
            addCriterion("CREATEYEAR is not null");
            return (Criteria) this;
        }

        public Criteria andCreateyearEqualTo(Short value) {
            addCriterion("CREATEYEAR =", value, "createyear");
            return (Criteria) this;
        }

        public Criteria andCreateyearNotEqualTo(Short value) {
            addCriterion("CREATEYEAR <>", value, "createyear");
            return (Criteria) this;
        }

        public Criteria andCreateyearGreaterThan(Short value) {
            addCriterion("CREATEYEAR >", value, "createyear");
            return (Criteria) this;
        }

        public Criteria andCreateyearGreaterThanOrEqualTo(Short value) {
            addCriterion("CREATEYEAR >=", value, "createyear");
            return (Criteria) this;
        }

        public Criteria andCreateyearLessThan(Short value) {
            addCriterion("CREATEYEAR <", value, "createyear");
            return (Criteria) this;
        }

        public Criteria andCreateyearLessThanOrEqualTo(Short value) {
            addCriterion("CREATEYEAR <=", value, "createyear");
            return (Criteria) this;
        }

        public Criteria andCreateyearIn(List<Short> values) {
            addCriterion("CREATEYEAR in", values, "createyear");
            return (Criteria) this;
        }

        public Criteria andCreateyearNotIn(List<Short> values) {
            addCriterion("CREATEYEAR not in", values, "createyear");
            return (Criteria) this;
        }

        public Criteria andCreateyearBetween(Short value1, Short value2) {
            addCriterion("CREATEYEAR between", value1, value2, "createyear");
            return (Criteria) this;
        }

        public Criteria andCreateyearNotBetween(Short value1, Short value2) {
            addCriterion("CREATEYEAR not between", value1, value2, "createyear");
            return (Criteria) this;
        }

        public Criteria andIrpdfversionIsNull() {
            addCriterion("IRPDFVERSION is null");
            return (Criteria) this;
        }

        public Criteria andIrpdfversionIsNotNull() {
            addCriterion("IRPDFVERSION is not null");
            return (Criteria) this;
        }

        public Criteria andIrpdfversionEqualTo(String value) {
            addCriterion("IRPDFVERSION =", value, "irpdfversion");
            return (Criteria) this;
        }

        public Criteria andIrpdfversionNotEqualTo(String value) {
            addCriterion("IRPDFVERSION <>", value, "irpdfversion");
            return (Criteria) this;
        }

        public Criteria andIrpdfversionGreaterThan(String value) {
            addCriterion("IRPDFVERSION >", value, "irpdfversion");
            return (Criteria) this;
        }

        public Criteria andIrpdfversionGreaterThanOrEqualTo(String value) {
            addCriterion("IRPDFVERSION >=", value, "irpdfversion");
            return (Criteria) this;
        }

        public Criteria andIrpdfversionLessThan(String value) {
            addCriterion("IRPDFVERSION <", value, "irpdfversion");
            return (Criteria) this;
        }

        public Criteria andIrpdfversionLessThanOrEqualTo(String value) {
            addCriterion("IRPDFVERSION <=", value, "irpdfversion");
            return (Criteria) this;
        }

        public Criteria andIrpdfversionLike(String value) {
            addCriterion("IRPDFVERSION like", value, "irpdfversion");
            return (Criteria) this;
        }

        public Criteria andIrpdfversionNotLike(String value) {
            addCriterion("IRPDFVERSION not like", value, "irpdfversion");
            return (Criteria) this;
        }

        public Criteria andIrpdfversionIn(List<String> values) {
            addCriterion("IRPDFVERSION in", values, "irpdfversion");
            return (Criteria) this;
        }

        public Criteria andIrpdfversionNotIn(List<String> values) {
            addCriterion("IRPDFVERSION not in", values, "irpdfversion");
            return (Criteria) this;
        }

        public Criteria andIrpdfversionBetween(String value1, String value2) {
            addCriterion("IRPDFVERSION between", value1, value2, "irpdfversion");
            return (Criteria) this;
        }

        public Criteria andIrpdfversionNotBetween(String value1, String value2) {
            addCriterion("IRPDFVERSION not between", value1, value2, "irpdfversion");
            return (Criteria) this;
        }

        public Criteria andDatasourceIsNull() {
            addCriterion("DATASOURCE is null");
            return (Criteria) this;
        }

        public Criteria andDatasourceIsNotNull() {
            addCriterion("DATASOURCE is not null");
            return (Criteria) this;
        }

        public Criteria andDatasourceEqualTo(String value) {
            addCriterion("DATASOURCE =", value, "datasource");
            return (Criteria) this;
        }

        public Criteria andDatasourceNotEqualTo(String value) {
            addCriterion("DATASOURCE <>", value, "datasource");
            return (Criteria) this;
        }

        public Criteria andDatasourceGreaterThan(String value) {
            addCriterion("DATASOURCE >", value, "datasource");
            return (Criteria) this;
        }

        public Criteria andDatasourceGreaterThanOrEqualTo(String value) {
            addCriterion("DATASOURCE >=", value, "datasource");
            return (Criteria) this;
        }

        public Criteria andDatasourceLessThan(String value) {
            addCriterion("DATASOURCE <", value, "datasource");
            return (Criteria) this;
        }

        public Criteria andDatasourceLessThanOrEqualTo(String value) {
            addCriterion("DATASOURCE <=", value, "datasource");
            return (Criteria) this;
        }

        public Criteria andDatasourceLike(String value) {
            addCriterion("DATASOURCE like", value, "datasource");
            return (Criteria) this;
        }

        public Criteria andDatasourceNotLike(String value) {
            addCriterion("DATASOURCE not like", value, "datasource");
            return (Criteria) this;
        }

        public Criteria andDatasourceIn(List<String> values) {
            addCriterion("DATASOURCE in", values, "datasource");
            return (Criteria) this;
        }

        public Criteria andDatasourceNotIn(List<String> values) {
            addCriterion("DATASOURCE not in", values, "datasource");
            return (Criteria) this;
        }

        public Criteria andDatasourceBetween(String value1, String value2) {
            addCriterion("DATASOURCE between", value1, value2, "datasource");
            return (Criteria) this;
        }

        public Criteria andDatasourceNotBetween(String value1, String value2) {
            addCriterion("DATASOURCE not between", value1, value2, "datasource");
            return (Criteria) this;
        }

        public Criteria andSourcepclidIsNull() {
            addCriterion("SOURCEPCLID is null");
            return (Criteria) this;
        }

        public Criteria andSourcepclidIsNotNull() {
            addCriterion("SOURCEPCLID is not null");
            return (Criteria) this;
        }

        public Criteria andSourcepclidEqualTo(Long value) {
            addCriterion("SOURCEPCLID =", value, "sourcepclid");
            return (Criteria) this;
        }

        public Criteria andSourcepclidNotEqualTo(Long value) {
            addCriterion("SOURCEPCLID <>", value, "sourcepclid");
            return (Criteria) this;
        }

        public Criteria andSourcepclidGreaterThan(Long value) {
            addCriterion("SOURCEPCLID >", value, "sourcepclid");
            return (Criteria) this;
        }

        public Criteria andSourcepclidGreaterThanOrEqualTo(Long value) {
            addCriterion("SOURCEPCLID >=", value, "sourcepclid");
            return (Criteria) this;
        }

        public Criteria andSourcepclidLessThan(Long value) {
            addCriterion("SOURCEPCLID <", value, "sourcepclid");
            return (Criteria) this;
        }

        public Criteria andSourcepclidLessThanOrEqualTo(Long value) {
            addCriterion("SOURCEPCLID <=", value, "sourcepclid");
            return (Criteria) this;
        }

        public Criteria andSourcepclidIn(List<Long> values) {
            addCriterion("SOURCEPCLID in", values, "sourcepclid");
            return (Criteria) this;
        }

        public Criteria andSourcepclidNotIn(List<Long> values) {
            addCriterion("SOURCEPCLID not in", values, "sourcepclid");
            return (Criteria) this;
        }

        public Criteria andSourcepclidBetween(Long value1, Long value2) {
            addCriterion("SOURCEPCLID between", value1, value2, "sourcepclid");
            return (Criteria) this;
        }

        public Criteria andSourcepclidNotBetween(Long value1, Long value2) {
            addCriterion("SOURCEPCLID not between", value1, value2, "sourcepclid");
            return (Criteria) this;
        }

        public Criteria andSourcestatusIsNull() {
            addCriterion("SOURCESTATUS is null");
            return (Criteria) this;
        }

        public Criteria andSourcestatusIsNotNull() {
            addCriterion("SOURCESTATUS is not null");
            return (Criteria) this;
        }

        public Criteria andSourcestatusEqualTo(String value) {
            addCriterion("SOURCESTATUS =", value, "sourcestatus");
            return (Criteria) this;
        }

        public Criteria andSourcestatusNotEqualTo(String value) {
            addCriterion("SOURCESTATUS <>", value, "sourcestatus");
            return (Criteria) this;
        }

        public Criteria andSourcestatusGreaterThan(String value) {
            addCriterion("SOURCESTATUS >", value, "sourcestatus");
            return (Criteria) this;
        }

        public Criteria andSourcestatusGreaterThanOrEqualTo(String value) {
            addCriterion("SOURCESTATUS >=", value, "sourcestatus");
            return (Criteria) this;
        }

        public Criteria andSourcestatusLessThan(String value) {
            addCriterion("SOURCESTATUS <", value, "sourcestatus");
            return (Criteria) this;
        }

        public Criteria andSourcestatusLessThanOrEqualTo(String value) {
            addCriterion("SOURCESTATUS <=", value, "sourcestatus");
            return (Criteria) this;
        }

        public Criteria andSourcestatusLike(String value) {
            addCriterion("SOURCESTATUS like", value, "sourcestatus");
            return (Criteria) this;
        }

        public Criteria andSourcestatusNotLike(String value) {
            addCriterion("SOURCESTATUS not like", value, "sourcestatus");
            return (Criteria) this;
        }

        public Criteria andSourcestatusIn(List<String> values) {
            addCriterion("SOURCESTATUS in", values, "sourcestatus");
            return (Criteria) this;
        }

        public Criteria andSourcestatusNotIn(List<String> values) {
            addCriterion("SOURCESTATUS not in", values, "sourcestatus");
            return (Criteria) this;
        }

        public Criteria andSourcestatusBetween(String value1, String value2) {
            addCriterion("SOURCESTATUS between", value1, value2, "sourcestatus");
            return (Criteria) this;
        }

        public Criteria andSourcestatusNotBetween(String value1, String value2) {
            addCriterion("SOURCESTATUS not between", value1, value2, "sourcestatus");
            return (Criteria) this;
        }

        public Criteria andSourcestatuslastmodDtIsNull() {
            addCriterion("SOURCESTATUSLASTMOD_DT is null");
            return (Criteria) this;
        }

        public Criteria andSourcestatuslastmodDtIsNotNull() {
            addCriterion("SOURCESTATUSLASTMOD_DT is not null");
            return (Criteria) this;
        }

        public Criteria andSourcestatuslastmodDtEqualTo(Date value) {
            addCriterionForJDBCDate("SOURCESTATUSLASTMOD_DT =", value, "sourcestatuslastmodDt");
            return (Criteria) this;
        }

        public Criteria andSourcestatuslastmodDtNotEqualTo(Date value) {
            addCriterionForJDBCDate("SOURCESTATUSLASTMOD_DT <>", value, "sourcestatuslastmodDt");
            return (Criteria) this;
        }

        public Criteria andSourcestatuslastmodDtGreaterThan(Date value) {
            addCriterionForJDBCDate("SOURCESTATUSLASTMOD_DT >", value, "sourcestatuslastmodDt");
            return (Criteria) this;
        }

        public Criteria andSourcestatuslastmodDtGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("SOURCESTATUSLASTMOD_DT >=", value, "sourcestatuslastmodDt");
            return (Criteria) this;
        }

        public Criteria andSourcestatuslastmodDtLessThan(Date value) {
            addCriterionForJDBCDate("SOURCESTATUSLASTMOD_DT <", value, "sourcestatuslastmodDt");
            return (Criteria) this;
        }

        public Criteria andSourcestatuslastmodDtLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("SOURCESTATUSLASTMOD_DT <=", value, "sourcestatuslastmodDt");
            return (Criteria) this;
        }

        public Criteria andSourcestatuslastmodDtIn(List<Date> values) {
            addCriterionForJDBCDate("SOURCESTATUSLASTMOD_DT in", values, "sourcestatuslastmodDt");
            return (Criteria) this;
        }

        public Criteria andSourcestatuslastmodDtNotIn(List<Date> values) {
            addCriterionForJDBCDate("SOURCESTATUSLASTMOD_DT not in", values, "sourcestatuslastmodDt");
            return (Criteria) this;
        }

        public Criteria andSourcestatuslastmodDtBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("SOURCESTATUSLASTMOD_DT between", value1, value2, "sourcestatuslastmodDt");
            return (Criteria) this;
        }

        public Criteria andSourcestatuslastmodDtNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("SOURCESTATUSLASTMOD_DT not between", value1, value2, "sourcestatuslastmodDt");
            return (Criteria) this;
        }

        public Criteria andLastsourcesyncDtIsNull() {
            addCriterion("LASTSOURCESYNC_DT is null");
            return (Criteria) this;
        }

        public Criteria andLastsourcesyncDtIsNotNull() {
            addCriterion("LASTSOURCESYNC_DT is not null");
            return (Criteria) this;
        }

        public Criteria andLastsourcesyncDtEqualTo(Date value) {
            addCriterionForJDBCDate("LASTSOURCESYNC_DT =", value, "lastsourcesyncDt");
            return (Criteria) this;
        }

        public Criteria andLastsourcesyncDtNotEqualTo(Date value) {
            addCriterionForJDBCDate("LASTSOURCESYNC_DT <>", value, "lastsourcesyncDt");
            return (Criteria) this;
        }

        public Criteria andLastsourcesyncDtGreaterThan(Date value) {
            addCriterionForJDBCDate("LASTSOURCESYNC_DT >", value, "lastsourcesyncDt");
            return (Criteria) this;
        }

        public Criteria andLastsourcesyncDtGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("LASTSOURCESYNC_DT >=", value, "lastsourcesyncDt");
            return (Criteria) this;
        }

        public Criteria andLastsourcesyncDtLessThan(Date value) {
            addCriterionForJDBCDate("LASTSOURCESYNC_DT <", value, "lastsourcesyncDt");
            return (Criteria) this;
        }

        public Criteria andLastsourcesyncDtLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("LASTSOURCESYNC_DT <=", value, "lastsourcesyncDt");
            return (Criteria) this;
        }

        public Criteria andLastsourcesyncDtIn(List<Date> values) {
            addCriterionForJDBCDate("LASTSOURCESYNC_DT in", values, "lastsourcesyncDt");
            return (Criteria) this;
        }

        public Criteria andLastsourcesyncDtNotIn(List<Date> values) {
            addCriterionForJDBCDate("LASTSOURCESYNC_DT not in", values, "lastsourcesyncDt");
            return (Criteria) this;
        }

        public Criteria andLastsourcesyncDtBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("LASTSOURCESYNC_DT between", value1, value2, "lastsourcesyncDt");
            return (Criteria) this;
        }

        public Criteria andLastsourcesyncDtNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("LASTSOURCESYNC_DT not between", value1, value2, "lastsourcesyncDt");
            return (Criteria) this;
        }

        public Criteria andLockversionFlgIsNull() {
            addCriterion("LOCKVERSION_FLG is null");
            return (Criteria) this;
        }

        public Criteria andLockversionFlgIsNotNull() {
            addCriterion("LOCKVERSION_FLG is not null");
            return (Criteria) this;
        }

        public Criteria andLockversionFlgEqualTo(String value) {
            addCriterion("LOCKVERSION_FLG =", value, "lockversionFlg");
            return (Criteria) this;
        }

        public Criteria andLockversionFlgNotEqualTo(String value) {
            addCriterion("LOCKVERSION_FLG <>", value, "lockversionFlg");
            return (Criteria) this;
        }

        public Criteria andLockversionFlgGreaterThan(String value) {
            addCriterion("LOCKVERSION_FLG >", value, "lockversionFlg");
            return (Criteria) this;
        }

        public Criteria andLockversionFlgGreaterThanOrEqualTo(String value) {
            addCriterion("LOCKVERSION_FLG >=", value, "lockversionFlg");
            return (Criteria) this;
        }

        public Criteria andLockversionFlgLessThan(String value) {
            addCriterion("LOCKVERSION_FLG <", value, "lockversionFlg");
            return (Criteria) this;
        }

        public Criteria andLockversionFlgLessThanOrEqualTo(String value) {
            addCriterion("LOCKVERSION_FLG <=", value, "lockversionFlg");
            return (Criteria) this;
        }

        public Criteria andLockversionFlgLike(String value) {
            addCriterion("LOCKVERSION_FLG like", value, "lockversionFlg");
            return (Criteria) this;
        }

        public Criteria andLockversionFlgNotLike(String value) {
            addCriterion("LOCKVERSION_FLG not like", value, "lockversionFlg");
            return (Criteria) this;
        }

        public Criteria andLockversionFlgIn(List<String> values) {
            addCriterion("LOCKVERSION_FLG in", values, "lockversionFlg");
            return (Criteria) this;
        }

        public Criteria andLockversionFlgNotIn(List<String> values) {
            addCriterion("LOCKVERSION_FLG not in", values, "lockversionFlg");
            return (Criteria) this;
        }

        public Criteria andLockversionFlgBetween(String value1, String value2) {
            addCriterion("LOCKVERSION_FLG between", value1, value2, "lockversionFlg");
            return (Criteria) this;
        }

        public Criteria andLockversionFlgNotBetween(String value1, String value2) {
            addCriterion("LOCKVERSION_FLG not between", value1, value2, "lockversionFlg");
            return (Criteria) this;
        }

        public Criteria andOwnerIsNull() {
            addCriterion("OWNER is null");
            return (Criteria) this;
        }

        public Criteria andOwnerIsNotNull() {
            addCriterion("OWNER is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerEqualTo(Long value) {
            addCriterion("OWNER =", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotEqualTo(Long value) {
            addCriterion("OWNER <>", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerGreaterThan(Long value) {
            addCriterion("OWNER >", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerGreaterThanOrEqualTo(Long value) {
            addCriterion("OWNER >=", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerLessThan(Long value) {
            addCriterion("OWNER <", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerLessThanOrEqualTo(Long value) {
            addCriterion("OWNER <=", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerIn(List<Long> values) {
            addCriterion("OWNER in", values, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotIn(List<Long> values) {
            addCriterion("OWNER not in", values, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerBetween(Long value1, Long value2) {
            addCriterion("OWNER between", value1, value2, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotBetween(Long value1, Long value2) {
            addCriterion("OWNER not between", value1, value2, "owner");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PROTOCOL
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PROTOCOL
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}