package model;

import java.util.Date;

public class Protocol {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROTOCOL.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROTOCOL.DCPID
     *
     * @mbggenerated
     */
    private Long dcpid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROTOCOL.PROTOCOLNUM
     *
     * @mbggenerated
     */
    private String protocolnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROTOCOL.TEMPNUM
     *
     * @mbggenerated
     */
    private String tempnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROTOCOL.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROTOCOL.INSTITUTE
     *
     * @mbggenerated
     */
    private String institute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROTOCOL.TECHTXRNOTE
     *
     * @mbggenerated
     */
    private String techtxrnote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROTOCOL.AGREEMENTNUM
     *
     * @mbggenerated
     */
    private String agreementnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROTOCOL.AGREEMENTTYPE
     *
     * @mbggenerated
     */
    private String agreementtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROTOCOL.CREATEYEAR
     *
     * @mbggenerated
     */
    private Short createyear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROTOCOL.IRPDFVERSION
     *
     * @mbggenerated
     */
    private String irpdfversion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROTOCOL.DATASOURCE
     *
     * @mbggenerated
     */
    private String datasource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROTOCOL.SOURCEPCLID
     *
     * @mbggenerated
     */
    private Long sourcepclid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROTOCOL.SOURCESTATUS
     *
     * @mbggenerated
     */
    private String sourcestatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROTOCOL.SOURCESTATUSLASTMOD_DT
     *
     * @mbggenerated
     */
    private Date sourcestatuslastmodDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROTOCOL.LASTSOURCESYNC_DT
     *
     * @mbggenerated
     */
    private Date lastsourcesyncDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROTOCOL.LOCKVERSION_FLG
     *
     * @mbggenerated
     */
    private String lockversionFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROTOCOL.OWNER
     *
     * @mbggenerated
     */
    private Long owner;
    
    //private Form form;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROTOCOL.ID
     *
     * @return the value of PROTOCOL.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROTOCOL.ID
     *
     * @param id the value for PROTOCOL.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROTOCOL.DCPID
     *
     * @return the value of PROTOCOL.DCPID
     *
     * @mbggenerated
     */
    public Long getDcpid() {
        return dcpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROTOCOL.DCPID
     *
     * @param dcpid the value for PROTOCOL.DCPID
     *
     * @mbggenerated
     */
    public void setDcpid(Long dcpid) {
        this.dcpid = dcpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROTOCOL.PROTOCOLNUM
     *
     * @return the value of PROTOCOL.PROTOCOLNUM
     *
     * @mbggenerated
     */
    public String getProtocolnum() {
        return protocolnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROTOCOL.PROTOCOLNUM
     *
     * @param protocolnum the value for PROTOCOL.PROTOCOLNUM
     *
     * @mbggenerated
     */
    public void setProtocolnum(String protocolnum) {
        this.protocolnum = protocolnum == null ? null : protocolnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROTOCOL.TEMPNUM
     *
     * @return the value of PROTOCOL.TEMPNUM
     *
     * @mbggenerated
     */
    public String getTempnum() {
        return tempnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROTOCOL.TEMPNUM
     *
     * @param tempnum the value for PROTOCOL.TEMPNUM
     *
     * @mbggenerated
     */
    public void setTempnum(String tempnum) {
        this.tempnum = tempnum == null ? null : tempnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROTOCOL.STATUS
     *
     * @return the value of PROTOCOL.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROTOCOL.STATUS
     *
     * @param status the value for PROTOCOL.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROTOCOL.INSTITUTE
     *
     * @return the value of PROTOCOL.INSTITUTE
     *
     * @mbggenerated
     */
    public String getInstitute() {
        return institute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROTOCOL.INSTITUTE
     *
     * @param institute the value for PROTOCOL.INSTITUTE
     *
     * @mbggenerated
     */
    public void setInstitute(String institute) {
        this.institute = institute == null ? null : institute.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROTOCOL.TECHTXRNOTE
     *
     * @return the value of PROTOCOL.TECHTXRNOTE
     *
     * @mbggenerated
     */
    public String getTechtxrnote() {
        return techtxrnote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROTOCOL.TECHTXRNOTE
     *
     * @param techtxrnote the value for PROTOCOL.TECHTXRNOTE
     *
     * @mbggenerated
     */
    public void setTechtxrnote(String techtxrnote) {
        this.techtxrnote = techtxrnote == null ? null : techtxrnote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROTOCOL.AGREEMENTNUM
     *
     * @return the value of PROTOCOL.AGREEMENTNUM
     *
     * @mbggenerated
     */
    public String getAgreementnum() {
        return agreementnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROTOCOL.AGREEMENTNUM
     *
     * @param agreementnum the value for PROTOCOL.AGREEMENTNUM
     *
     * @mbggenerated
     */
    public void setAgreementnum(String agreementnum) {
        this.agreementnum = agreementnum == null ? null : agreementnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROTOCOL.AGREEMENTTYPE
     *
     * @return the value of PROTOCOL.AGREEMENTTYPE
     *
     * @mbggenerated
     */
    public String getAgreementtype() {
        return agreementtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROTOCOL.AGREEMENTTYPE
     *
     * @param agreementtype the value for PROTOCOL.AGREEMENTTYPE
     *
     * @mbggenerated
     */
    public void setAgreementtype(String agreementtype) {
        this.agreementtype = agreementtype == null ? null : agreementtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROTOCOL.CREATEYEAR
     *
     * @return the value of PROTOCOL.CREATEYEAR
     *
     * @mbggenerated
     */
    public Short getCreateyear() {
        return createyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROTOCOL.CREATEYEAR
     *
     * @param createyear the value for PROTOCOL.CREATEYEAR
     *
     * @mbggenerated
     */
    public void setCreateyear(Short createyear) {
        this.createyear = createyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROTOCOL.IRPDFVERSION
     *
     * @return the value of PROTOCOL.IRPDFVERSION
     *
     * @mbggenerated
     */
    public String getIrpdfversion() {
        return irpdfversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROTOCOL.IRPDFVERSION
     *
     * @param irpdfversion the value for PROTOCOL.IRPDFVERSION
     *
     * @mbggenerated
     */
    public void setIrpdfversion(String irpdfversion) {
        this.irpdfversion = irpdfversion == null ? null : irpdfversion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROTOCOL.DATASOURCE
     *
     * @return the value of PROTOCOL.DATASOURCE
     *
     * @mbggenerated
     */
    public String getDatasource() {
        return datasource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROTOCOL.DATASOURCE
     *
     * @param datasource the value for PROTOCOL.DATASOURCE
     *
     * @mbggenerated
     */
    public void setDatasource(String datasource) {
        this.datasource = datasource == null ? null : datasource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROTOCOL.SOURCEPCLID
     *
     * @return the value of PROTOCOL.SOURCEPCLID
     *
     * @mbggenerated
     */
    public Long getSourcepclid() {
        return sourcepclid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROTOCOL.SOURCEPCLID
     *
     * @param sourcepclid the value for PROTOCOL.SOURCEPCLID
     *
     * @mbggenerated
     */
    public void setSourcepclid(Long sourcepclid) {
        this.sourcepclid = sourcepclid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROTOCOL.SOURCESTATUS
     *
     * @return the value of PROTOCOL.SOURCESTATUS
     *
     * @mbggenerated
     */
    public String getSourcestatus() {
        return sourcestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROTOCOL.SOURCESTATUS
     *
     * @param sourcestatus the value for PROTOCOL.SOURCESTATUS
     *
     * @mbggenerated
     */
    public void setSourcestatus(String sourcestatus) {
        this.sourcestatus = sourcestatus == null ? null : sourcestatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROTOCOL.SOURCESTATUSLASTMOD_DT
     *
     * @return the value of PROTOCOL.SOURCESTATUSLASTMOD_DT
     *
     * @mbggenerated
     */
    public Date getSourcestatuslastmodDt() {
        return sourcestatuslastmodDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROTOCOL.SOURCESTATUSLASTMOD_DT
     *
     * @param sourcestatuslastmodDt the value for PROTOCOL.SOURCESTATUSLASTMOD_DT
     *
     * @mbggenerated
     */
    public void setSourcestatuslastmodDt(Date sourcestatuslastmodDt) {
        this.sourcestatuslastmodDt = sourcestatuslastmodDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROTOCOL.LASTSOURCESYNC_DT
     *
     * @return the value of PROTOCOL.LASTSOURCESYNC_DT
     *
     * @mbggenerated
     */
    public Date getLastsourcesyncDt() {
        return lastsourcesyncDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROTOCOL.LASTSOURCESYNC_DT
     *
     * @param lastsourcesyncDt the value for PROTOCOL.LASTSOURCESYNC_DT
     *
     * @mbggenerated
     */
    public void setLastsourcesyncDt(Date lastsourcesyncDt) {
        this.lastsourcesyncDt = lastsourcesyncDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROTOCOL.LOCKVERSION_FLG
     *
     * @return the value of PROTOCOL.LOCKVERSION_FLG
     *
     * @mbggenerated
     */
    public String getLockversionFlg() {
        return lockversionFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROTOCOL.LOCKVERSION_FLG
     *
     * @param lockversionFlg the value for PROTOCOL.LOCKVERSION_FLG
     *
     * @mbggenerated
     */
    public void setLockversionFlg(String lockversionFlg) {
        this.lockversionFlg = lockversionFlg == null ? null : lockversionFlg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROTOCOL.OWNER
     *
     * @return the value of PROTOCOL.OWNER
     *
     * @mbggenerated
     */
    public Long getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROTOCOL.OWNER
     *
     * @param owner the value for PROTOCOL.OWNER
     *
     * @mbggenerated
     */
    public void setOwner(Long owner) {
        this.owner = owner;
    }

    /*public Form getForm() {
      return form;
    }

    public void setForm(Form form) {
      this.form = form;
    }*/
}